DROP PROCEDURE MCLISOLIB.NCOVCTR

CREATE OR REPLACE PROCEDURE MCLISOLIB.NCOVCTR (IN I_COR VARCHAR(3)
											  , IN I_UID VARCHAR(12)
											  , IN I_IP  VARCHAR(30)
											  , IN I_DAT  DECIMAL(8,0)
									  		  , IN I_JNO  DECIMAL(5,0)
											  , OUT O_MSGCOD VARCHAR(3)
											  , OUT O_ERRCOD VARCHAR(10)
											  )
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
	--코로나 CT 값 조회
	DECLARE CUR1 CURSOR FOR
		SELECT COALESCE(CONCAT('E Gene : ',NCOVEGN),'') AS CT1
				, COALESCE(CONCAT('RdRP Gene : ',NCOVRGN),'') AS CT2
				, COALESCE(CONCAT('N Gene : ',NCOVNGN),'') AS CT3
		FROM MCLISDLIB.NCOVCT@ AA, MCLISDLIB.MC600M@ BB
		WHERE AA.NCOVCOR = BB.F600COR
		AND AA.NCOVDAT = BB.F600DAT
		AND AA.NCOVJNO = BB.F600JNO
		AND AA.NCOVCOR = I_COR
		AND AA.NCOVDAT = I_DAT
		AND AA.NCOVJNO = I_JNO
		AND BB . F600C03 = 'Y' AND BB . F600C04 = '9' -- 완료된 결과만 
		AND UPPER(BB.F600CHR) in ('POSITIVE','INCONCLUSIVE (미결정)');  
	SET O_ERRCOD = '' ;
	SET O_MSGCOD = 200 ;
	OPEN CUR1; SET RESULT SETS CURSOR CUR1;
END 