--  Generate SQL 
--  Version:                   V7R2M0 140418 
--  Generated on:              21/10/23 10:40:50 
--  Relational Database:       NEODIN 
--  Standards Option:          DB2 for i 
DROP SPECIFIC PROCEDURE MCLISOLIB.UPD_SMS_SEND_FLAG ; 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","NEO018" ; 
CREATE OR REPLACE PROCEDURE MCLISOLIB.UPD_SMS_SEND_FLAG ( 
  IN $I_DAT DECIMAL(8, 0) , 
  IN $I_JNO DECIMAL(5, 0) , 
  IN $I_HOS VARCHAR(5) , 
  IN $I_REPORT_KEY VARCHAR(100) ) 
  LANGUAGE SQL 
  SPECIFIC MCLISOLIB.UPD_SMS_SEND_FLAG 
  NOT DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION  ALWBLK = *ALLREAD , 
  ALWCPYDTA = *OPTIMIZE , 
  COMMIT = *NONE , 
  DECRESULT = (31, 31, 00) , 
  DYNDFTCOL = *NO , 
  DYNUSRPRF = *USER , 
  SRTSEQ = *HEX 
  BEGIN 
		UPDATE MCLISDLIB . "MC100HSUB@" SET S100TMP6 = 'Y' , S100TMP8 = $I_REPORT_KEY 
		WHERE S100COR = 'NML' 
		AND S100DAT = $I_DAT 
		AND S100JNO = $I_JNO 
		AND S100HOS = $I_HOS 
		; 
END  ; 
