--  Generate SQL 
--  Version:                   V7R2M0 140418 
--  Generated on:              22/09/02 17:43:08 
--  Relational Database:       NEODIN 
--  Standards Option:          DB2 for i 
--DROP SPECIFIC PROCEDURE MCLISOLIB.SEL_FISHHOMEPAGE_RESULTTEXT_SGFIRH_SP ; 
--SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","NEO018" ; 
CREATE OR REPLACE PROCEDURE MCLISOLIB.SEL_FISHHOMEPAGE_RESULTTEXT_SGFIRH_SP ( 
  IN $P_COR CHAR(3) , 
  IN $P_DAT DECIMAL(8, 0) , 
  IN $P_JNO DECIMAL(5, 0) ) 
  DYNAMIC RESULT SETS 1 
  LANGUAGE SQL 
  SPECIFIC MCLISOLIB.SEL_FISHHOMEPAGE_RESULTTEXT_SGFIRH_SP 
  NOT DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION  ALWBLK = *ALLREAD , 
  ALWCPYDTA = *OPTIMIZE , 
  COMMIT = *NONE , 
  DBGVIEW = *SOURCE , 
  DECRESULT = (31, 31, 00) , 
  DFTRDBCOL = *NONE , 
  DLYPRP = *NO , 
  DYNDFTCOL = *NO , 
  DYNUSRPRF = *USER , 
  SRTSEQ = *HEX 
  BEGIN 
	DECLARE CUR CURSOR FOR 
	 
SELECT 
	REPLACE ( FFIRTXT , CHR ( 13 ) || CHR ( 10 ) , '<br>' ) AS FFIRTXT	 
FROM MCLISDLIB . SGFIRH@ 
WHERE	1 = 1 
AND		FFIRCOR	= $P_COR 
AND	FFIRDAT	= $P_DAT 
AND	FFIRJNO	= $P_JNO 
; 
OPEN CUR ; 
SET RESULT SETS CURSOR CUR ; 
END  ; 
