--  Generate SQL 
--  Version:                   V7R2M0 140418 
--  Generated on:              22/04/28 10:46:23 
--  Relational Database:       NEODIN 
--  Standards Option:          DB2 for i 
--DROP SPECIFIC PROCEDURE MCLISOLIB.UPD_SMS_SEND_FLAG_CANCEL ; 
--SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","NEO018" ; 
CREATE OR REPLACE PROCEDURE MCLISOLIB.UPD_SMS_SEND_FLAG_CANCEL ( 
  IN $I_DAT DECIMAL(8, 0) , 
  IN $I_JNO DECIMAL(5, 0) , 
  IN $I_HOS VARCHAR(5) ,
  IN $I_SEQ VARCHAR(1000) 
  ) 
  LANGUAGE SQL 
  SPECIFIC MCLISOLIB.UPD_SMS_SEND_FLAG_CANCEL 
  NOT DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION  ALWBLK = *ALLREAD , 
  ALWCPYDTA = *OPTIMIZE , 
  COMMIT = *NONE , 
  DECRESULT = (31, 31, 00) , 
  DYNDFTCOL = *NO , 
  DYNUSRPRF = *USER , 
  SRTSEQ = *HEX 
  BEGIN 
		UPDATE MCLISDLIB . SMSREVISE SET FSMSSYN = 'Y' 
		WHERE 1 = 1 
		AND FSMSCOR = 'NML' 
		AND FSMSDAT = $I_DAT 
		AND FSMSJNO = $I_JNO 
		AND FSMSHOS = $I_HOS 
		AND FSMSSEQ = $I_SEQ 
		; 
END  ; 
