--  Generate SQL 
--  Version:                   V7R2M0 140418 
--  Generated on:              22/04/28 10:01:30 
--  Relational Database:       NEODIN 
--  Standards Option:          DB2 for i 
--DROP SPECIFIC PROCEDURE MCLISOLIB.SEL_SMS_SEND_DATA_CANCEL ; 
--SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","NEO018" ; 
CREATE OR REPLACE PROCEDURE MCLISOLIB.SEL_SMS_SEND_DATA_CANCEL ( 
  IN $I_HOS VARCHAR(5) ) 
  DYNAMIC RESULT SETS 1 
  LANGUAGE SQL 
  SPECIFIC MCLISOLIB.SEL_SMS_SEND_DATA_CANCEL 
  NOT DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION  ALWBLK = *ALLREAD , 
  ALWCPYDTA = *OPTIMIZE , 
  COMMIT = *NONE , 
  DECRESULT = (31, 31, 00) , 
  DYNDFTCOL = *NO , 
  DYNUSRPRF = *USER , 
  SRTSEQ = *HEX 
  BEGIN 
	DECLARE CUR1 CURSOR FOR 
		SELECT FSMSDAT AS DAT 
				, FSMSJNO AS JNO 
				, FSMSGCD AS GCD 
				, FSMSACD AS ACD 
				, FSMSRST AS RST 
				, FSMSGNM AS GCD_NM
				, FSMSNAM AS NAM 
				, FSMSHOS AS HOS 
				, FSMSHNM AS HOS_NM 
				, FSMSPCD AS PCD 
				, FSMSSNN AS SNN 
				, FSMSPNO AS PNO 
				, FSMSFTM AS SMS_FR_TM 
				, FSMSTTM AS SMS_TO_TM 
				, FSMSTMP AS SMS_TEMPLATE 
				, FSMSSEX AS FSMSSEX 
				, FSMSBIR AS BIRTH 
				, FSMSSYN AS SENDYN 
				, FSMSSEQ AS SEQ 
		FROM MCLISDLIB . SMSREVISE 
		WHERE 1 = 1 
		AND ( IFNULL ( $I_HOS , '' ) = '' OR FSMSHOS = $I_HOS )  -- 병원코드 없으면 모든병원 / 병원코드 있으면 특정병원만 집계 
		AND trim(FSMSSYN) <> 'Y' 
		AND FSMSPCD = '82'
		AND IFNULL ( TRIM(FSMSSNN) , '' ) <> ''
		AND IFNULL ( TRIM(FSMSPNO) , '' ) <> ''
	; 
	OPEN CUR1 ; 
	SET RESULT SETS CURSOR CUR1 ; 
END  ; 
