DROP PROCEDURE WEBOBJLIB.MWS005C5;


CREATE PROCEDURE WEBOBJLIB.MWS005C5
(
	  IN  I_COR 	VARCHAR(3) 	-- COR
	, IN  I_UID 	VARCHAR(12) -- 사용자 ID
	, IN  I_HLK	  VARCHAR(30)	-- 로그인 IP
	, OUT O_RSTCOD	VARCHAR(1)		-- 메세지 코드
)
BEGIN

			-- 외부 로그인 난수 업데이트
		DECLARE T_CNT DECIMAL ( 1 , 0 ) ;
		
		SET O_RSTCOD = '' ;
		
		SELECT COUNT ( S005COR )
		INTO T_CNT
		FROM WEBDBLIB . MWS005M@
		WHERE S005COR = I_COR
		AND S005UID = I_UID ;
		
		IF T_CNT = 0 THEN
		SET O_RSTCOD = '1' ;
		END IF ;
		
			UPDATE WEBDBLIB . MWS005M@
			SET S005HLK = I_HLK
			WHERE S005COR = I_COR
			AND S005UID = I_UID ;
		
		COMMIT ;

	SET O_RSTCOD = 'O' ;

END                    