DROP PROCEDURE WEBOBJLIB.MWS005C4;

CREATE OR REPLACE PROCEDURE WEBOBJLIB.MWS005C4
(
	  IN  I_COR 		VARCHAR(3) 		-- COR
	, IN  I_UID 		VARCHAR(12) 	-- 사용자 ID
	, IN  I_IP	  		VARCHAR(30)		-- 로그인 IP
	, OUT O_MSGCOD		VARCHAR(3)		-- 메세지 코드
	, OUT O_ERRCOD		VARCHAR(10)		-- 에러 코드
	, IN  I_LOGLID		VARCHAR(12)		--	LOGIN ID
	, IN  I_SPWD		VARCHAR(8)		--	변경전 비밀번호
	, IN  I_PWD			VARCHAR(20)		--	변경후 비밀번호 
	, IN  I_SPWD_SHA	VARCHAR(1000)	--	변경전 비밀번호(SHA) 
	, IN  I_PWD_SHA		VARCHAR(1000)	--	변경후 비밀번호(SHA) 
)
BEGIN
	--비밀번호 변경
	DECLARE V_CNT DECIMAL(5,0);	-- 사용자 아이디

	SET O_MSGCOD = '300';
	SET O_ERRCOD = '';
	SET V_CNT = 0;

	SELECT COUNT(*) -- 사용자 아이디 체크
	INTO V_CNT
	FROM MCLISDLIB.MCPASW@T
	WHERE PASCOR = I_COR
	AND PASLID = I_LOGLID
	AND PASASW = I_SPWD_SHA;
	
	IF V_CNT = 0  THEN
		SET O_MSGCOD = '247';
	ELSE
		SET O_MSGCOD = '272';
		UPDATE MCLISDLIB.MCPASW@T
		SET PASASW = I_PWD_SHA
		WHERE PASCOR = I_COR
		AND PASLID = I_LOGLID;

		UPDATE WEBDBLIB.MWS005M@
		SET S005IYN = 'N'
		WHERE S005COR = I_COR
		AND S005UID = I_LOGLID;
	END IF;	--비밀번호 수정
END

