DROP PROCEDURE WEBOBJLIB.MWS011R;

CREATE PROCEDURE WEBOBJLIB.MWS011R
(
	  IN I_COR 		VARCHAR(3) 	-- COR
	, IN I_UID 		VARCHAR(12) -- 사용자 ID
	, IN I_IP	  	VARCHAR(30)	-- 로그인 IP
	, OUT O_MSGCOD	CHAR(3)	-- 메세지 코드
	, OUT O_ERRCOD	CHAR(10)	 -- 에러 코드
	, IN  I_RFM		VARCHAR(20)	  -- 폼
	, IN  I_RCL		VARCHAR(20)	 -- 양식지
	, IN  I_RTP		VARCHAR(20)	  -- 결과지 타입
)
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN	
	-- 폼별 결과 양식 관리 조회
   DECLARE CUR1  CURSOR WITH RETURN FOR
   SELECT S011COR
	,S011RFM		-- 폼
	,S011RCL		-- 양식지
	,S011RTP		-- 결과지 타입
   FROM WEBDBLIB.MWS011M@
   WHERE S011COR = I_COR
   AND (I_RFM = '' OR	S011RFM = I_RFM)	--폼
   AND (I_RCL = '' OR	S011RCL = I_RCL)	--양식지
   AND (I_RTP = '' OR	S011RTP = I_RTP)	--결과지타입
   ORDER BY S011COR ,S011RFM ,S011RCL	 ,S011RTP
   ;

	SET O_MSGCOD = '200';
   OPEN CUR1;
END