CREATE PROCEDURE WEBOBJLIB.MWS009R2
(	
	   IN  I_COR VARCHAR(3)
	 , IN  I_UID VARCHAR(12)
	 , IN  I_IP  VARCHAR(30)
	 , OUT O_MSGCOD VARCHAR(3)
	 , OUT O_ERRCOD VARCHAR(10)
     , IN  I_S009HOS VARCHAR(5)
)
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
	--엑셀접수포멧 데이터 조회
	DECLARE C1 CURSOR WITH RETURN FOR
SELECT *
FROM WEBDBLIB . "MWS009M@"
WHERE S009HOS = I_S009HOS ;
SET O_ERRCOD = '';
SET O_MSGCOD = 200 ;
	OPEN C1 ;
END