DROP PROCEDURE WEBOBJLIB.MWS011CC;


CREATE PROCEDURE WEBOBJLIB.MWS011CC
(
	  IN  I_COR 	VARCHAR(3) 	-- COR
	, IN  I_UID 	VARCHAR(12) -- 사용자 ID
	, IN  I_IP	  	VARCHAR(30)	-- 로그인 IP
	, OUT O_MSGCOD	VARCHAR(3)	-- 메세지 코드
	, OUT O_ERRCOD	VARCHAR(10)	-- 에러 코드
	, IN  I_RFM		VARCHAR(20)	  -- 폼
)BEGIN
	-- 폼별 결과 양식 관리 중복확인
	DECLARE V_CNT DECIMAL(5,0);	--  수량 확인

   SELECT  COUNT(*)
    INTO  V_CNT
   FROM WEBDBLIB.MWS011M@
   WHERE S011COR = I_COR
   AND S011RFM = I_RFM	--폼
   ;
   IF V_CNT >0 THEN
	SET O_MSGCOD = '202';
   ELSE
	SET O_MSGCOD = '200';
   END IF;

END