CREATE PROCEDURE WEBOBJLIB.MWS013DT (IN I_COR VARCHAR(3)
									  , IN I_UID VARCHAR(12)
									  , IN I_IP  VARCHAR(30)
									  , OUT O_MSGCOD VARCHAR(3)
									  , OUT O_ERRCOD VARCHAR(10)
									  )
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
	--날짜관련 조회
	DECLARE C1 CURSOR WITH RETURN FOR
		SELECT CURRENT_DATE AS A
		, DATE ( CURRENT_TIMESTAMP ) AS B
		, TO_CHAR ( CURRENT_TIMESTAMP , 'YYYYMM' ) AS C
		, TO_CHAR ( CURRENT_TIMESTAMP , 'YYYYMMDD' ) AS C2
		, SUBSTR ( HEX ( CURRENT_TIMESTAMP ) , 1 , 8 ) AS D
		, YEAR ( CURRENT_TIMESTAMP ) AS E
		, MONTH ( CURRENT_DATE ) AS F
		, DAY ( CURRENT_TIMESTAMP ) AS G
		, DAYS ( CURRENT_TIMESTAMP ) AS H
		, TIME ( CURRENT_TIMESTAMP ) AS I
		, CURRENT_TIME AS J
		, TO_CHAR ( CURRENT_TIMESTAMP , 'YYYY-MM-DD HH24:MI:SS' ) AS K
		, CHAR ( CURRENT TIMESTAMP )
		, CURRENT TIMESTAMP
		, TO_CHAR ( CURRENT_TIMESTAMP , 'NNNNNN' ) AS Z
		, DAYOFYEAR ( CURRENT_DATE ) AS L
		, WEEK ( CURRENT_DATE ) AS M
		, DAYOFWEEK ( CURRENT_DATE ) AS N
		, DAYOFWEEK_ISO ( CURRENT_DATE ) AS O
		, JULIAN_DAY ( CURRENT_DATE ) AS P
		, TO_CHAR ( CURRENT_TIMESTAMP , 'AM' ) AS Q
		, TIME ( CURRENT_TIMESTAMP ) + 12 HOUR AS R
		, DATE ( CURRENT_TIMESTAMP ) + 2 DAYS AS S
		, DATE ( CURRENT_TIMESTAMP ) + 2 MONTHS AS T
		FROM SYSIBM . SYSDUMMY1 ;
	SET O_ERRCOD = '';
	SET O_MSGCOD = 200 ;
	OPEN C1 ;
END 