DROP PROCEDURE WEBOBJLIB.MWS005C3;

CREATE OR REPLACE PROCEDURE WEBOBJLIB.MWS005C3
(
	  IN  I_COR 	VARCHAR(3) 	-- COR
	, IN  I_UID 	VARCHAR(12) -- 사용자 ID
	, IN  I_IP	  	VARCHAR(30)	-- 로그인 IP
	, OUT O_MSGCOD	VARCHAR(3)		-- 메세지 코드
	, OUT O_ERRCOD	VARCHAR(10)	-- 에러 코드
	, IN  I_LOGCOR	VARCHAR(3)	--	COR
	, IN  I_LOGLID	VARCHAR(12) --	LOGIN ID
	, IN  I_PASASW	VARCHAR(1000) --	비밀번호 
)
BEGIN
	--비밀번호 초기화
	DECLARE V_CNT DECIMAL(5,0);	-- 사용자 아이디

	SET O_MSGCOD = '300';
	SET O_ERRCOD = '';
	SET V_CNT = 0;

	SELECT COUNT(*) -- 사용자 아이디 체크
	INTO V_CNT
	FROM MCLISDLIB.MCPASW@T
	WHERE PASCOR = I_LOGCOR
	AND PASLID = I_LOGLID;
	
	IF V_CNT > 0  THEN
		SET O_MSGCOD = '221';
		UPDATE MCLISDLIB.MCPASW@T
		SET PASASW = I_PASASW
		WHERE PASCOR = I_LOGCOR
		AND PASLID = I_LOGLID;

		UPDATE WEBDBLIB.MWS005M@
		SET S005IYN = 'Y'
		WHERE S005COR = I_LOGCOR
		AND S005UID = I_LOGLID;
	END IF;	--비밀번호 수정
END


