DROP PROCEDURE WEBOBJLIB.MWR001A2

CREATE OR REPLACE PROCEDURE WEBOBJLIB.MWR001A2 (IN I_COR VARCHAR(3)
									  , IN I_UID VARCHAR(12)
									  , IN I_IP  VARCHAR(30)
									  , OUT O_MSGCOD VARCHAR(3)
									  , OUT O_ERRCOD VARCHAR(10)
									  , IN I_DAT  DECIMAL(8,0)
									  , IN I_JNO  DECIMAL(5,0)
									  , IN I_HOS  VARCHAR(5))
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN	
	-- 추가검사의뢰리스트를 별도로 관리한다.
	IF I_HOS = '12527' THEN
		BEGIN	
			--기타항목 리스트 조회
			DECLARE C1 CURSOR WITH RETURN FOR 
				SELECT 1 CHK
					  , A.R001GCD
					  , C.F010SNM
				FROM WEBDBLIB."MWR001D@" A LEFT OUTER JOIN mclisdlib.mc010m@ C
						ON A.R001GCD = C.F010GCD
				WHERE A.R001DAT = I_DAT
				AND A.R001JNO = I_JNO
				AND A.R001GCD NOT IN (SELECT R001GCD AS GCD
										  FROM WEBDBLIB.MWR001C@ A
										  WHERE A.R001COR = I_COR
										  AND A.R001HOS = I_HOS
										)
				ORDER BY A.R001GCD;
			SET O_ERRCOD = '';
			SET O_MSGCOD = 200;
			OPEN C1;
		END;
	ELSE
		BEGIN	
			--기타항목 리스트 조회
			DECLARE C2 CURSOR WITH RETURN FOR 
				SELECT 1 CHK
					  , A.R001GCD
					  , C.F010SNM
				FROM WEBDBLIB."MWR001D@" A LEFT OUTER JOIN mclisdlib.mc010m@ C
						ON A.R001GCD = C.F010GCD
				WHERE A.R001DAT = I_DAT
				AND A.R001JNO = I_JNO
				AND A.R001GCD NOT IN (SELECT R001GCD AS GCD
										  FROM WEBDBLIB.MWR001C@ A
										  WHERE A.R001COR = I_COR
										  AND A.R001HOS = ''
										)
				ORDER BY A.R001GCD;
			SET O_ERRCOD = '';
			SET O_MSGCOD = 200;
			OPEN C2;
		END;
	END IF;
END


