DROP PROCEDURE  WEBOBJLIB.MWS008MU;

CREATE PROCEDURE WEBOBJLIB.MWS008MU
(
	  IN I_COR 		VARCHAR(3) 		-- COR
	, IN I_UID 		VARCHAR(12) 	-- 사용자 ID
	, IN I_IP		VARCHAR(30)			-- 사용자 IP
	, OUT O_MSGCOD	VARCHAR(3)	-- 메세지 코드
	, OUT O_ERRCOD	VARCHAR(10) -- 에러 코드
	, IN I_MCD		VARCHAR(20)		-- 메뉴 코드
	, IN I_RCD		VARCHAR(20)		-- 검색어 코드	
	, IN I_VCD		VARCHAR(20)		-- 검색어 값 코드
)
BEGIN
	-- 메인 퀵셋업, 메뉴별 퀵셋업 수정 및 삭제
	IF I_VCD ='' THEN
		DELETE FROM
		WEBDBLIB."MWS008M@"
		WHERE S008COR = I_COR
			AND S008MCD = I_MCD
			AND S008RCD = I_RCD
			AND S008UID = I_UID;
	ELSE
		UPDATE WEBDBLIB."MWS008M@"
		SET
			 S008VCD = I_VCD
			,S008UUR = I_UID		
			,S008UDT = TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD')
			,S008UTM = TO_CHAR(CURRENT_TIMESTAMP, 'hh24miss')
			,S008UIP = I_IP		
		WHERE   S008COR = I_COR
			AND S008UID = I_UID	 
			AND S008MCD = I_MCD
			AND S008RCD = I_RCD;
	END IF; 
		
	SET O_MSGCOD = '200';
	SET O_ERRCOD = '';

END