CREATE PROCEDURE WEBOBJLIB.MWS014DR(
									IN  I_COR    VARCHAR(3)
								  , IN  I_UID    VARCHAR(12)
								  , IN  I_IP   	 VARCHAR(30)
     							  , OUT O_MSGCOD VARCHAR(3)
   								  , OUT O_ERRCOD VARCHAR(10)
   								  , IN  I_SEQ 	 DECIMAL(11,0))
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
   DECLARE C1 CURSOR WITH RETURN FOR
   SELECT
      S014SEQ,
      S014FPT,
      S014FNM,
      S014FSNM
   FROM WEBDBLIB."MWS014D@"
   WHERE S014SEQ = I_SEQ;
   SET O_MSGCOD = 200 ;
   OPEN C1 ;
END