CREATE PROCEDURE WEBOBJLIB.MWS013R2 (IN I_COR VARCHAR(3)
									  , IN I_UID VARCHAR(12)
									  , IN I_IP  VARCHAR(30)
									  , OUT O_MSGCOD VARCHAR(3)
									  , OUT O_ERRCOD VARCHAR(10)
									  , IN I_MCD  VARCHAR(20)
									  )
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
	--도움말 뷰 데이터 조회
	DECLARE C1 CURSOR WITH RETURN FOR
		SELECT S013MCD
			   ,S013CON 
		FROM WEBDBLIB.MWS013M@
		WHERE S013COR = I_COR
		AND   S013MCD = I_MCD;
	OPEN C1;
	SET O_ERRCOD = '';
	SET O_MSGCOD = 200;
END


