DROP PROCEDURE WEBOBJLIB.MWHOSLST2;

CREATE PROCEDURE WEBOBJLIB.MWHOSLST2
(
     IN I_COR       VARCHAR(3)       -- COR
   , IN I_UID       VARCHAR(12)    -- 사용자 ID
   , IN I_IP      VARCHAR(30)      -- 로그인 IP
   , OUT O_MSGCOD   VARCHAR(3)      -- 메세지 코드
   , OUT O_ERRCOD   VARCHAR(10)      -- 에러 코드
   , IN I_HOS      VARCHAR(5)      -- 병원 코드
)
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
	-- 병원 검색 팝업, 병원 코드로 병원 이름 가져오기
	DECLARE CUR1 CURSOR WITH RETURN FOR
	SELECT
	TRIM ( F120FNM ) F120FNM
	FROM MCLISDLIB . MC120M@
	WHERE F120COR = I_COR
	AND F120PCD = I_HOS
	ORDER BY F120PCD ;
	
	OPEN CUR1 ;
	SET O_MSGCOD = '200' ;
	SET O_ERRCOD = '' ;

END            