CREATE PROCEDURE WEBOBJLIB.MWS014MS1 (
									 	OUT O_MSGCOD VARCHAR(3)
                           			  , OUT O_ERRCOD VARCHAR(10)
									)
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
   DECLARE C1 CURSOR WITH RETURN FOR 
      SELECT NEXTVAL FOR WEBDBLIB.MWS014MSEQ S014SEQ FROM SYSIBM.SYSDUMMY1;
   SET O_MSGCOD = 200;
   OPEN C1;
END