CREATE PROCEDURE WEBOBJLIB.SUREDATAC
(
     IN I_COR VARCHAR(3)
  , IN I_UID VARCHAR(12)
  , IN I_IP  VARCHAR(30)
  , OUT O_MSGCOD VARCHAR(3)
  , OUT O_ERRCOD VARCHAR(10)
  , IN SENDNAM VARCHAR(32)
  , IN SENDHPN VARCHAR(20)
  , IN C001HPN VARCHAR(20)
  , IN C002MSG VARCHAR(4000)
  , IN NAM VARCHAR(32)
)
BEGIN
	--SMS 메시지 저장
INSERT INTO WEBDBLIB.SUREDATA
	(SEQNO -- 필수
	, INTIME -- 필수
	, USERCODE -- 필수
	, DEPTCODE
	, BIZTYPE
	, YELLOWID_KEY
	, REQNAME
	, REQPHONE -- 필수
	, CALLNAME
	, COUNTRY
	, CALLPHONE
	, SUBJECT
	, MSG
	, REQTIME
	, SENTTIME
	, RECVTIME
	, "RESULT"
	, ERRCODE
	, KIND
	, FKCONTENT
	, IMAGE_URL
	, BATCHFLAG
	, RETRY
	, RESEND
	, TEMPLATECODE
	, RETEXT
	, RESENTFLAG
	, SENTMEDIA
	, MEDIATYPE
	, BTN_TYPE_01
	, BTN_NM_01
	, BTN_01_URL_01
	, BTN_01_URL_02
	, BTN_TYPE_02
	, BTN_NM_02
	, BTN_02_URL_01
	, BTN_02_URL_02
	, BTN_TYPE_03
	, BTN_NM_03
	, BTN_03_URL_01
	, BTN_03_URL_02
	, BTN_TYPE_04
	, BTN_NM_04
	, BTN_04_URL_01
	, BTN_04_URL_02
	, BTN_TYPE_05
	, BTN_NM_05
	, BTN_05_URL_01
	, BTN_05_URL_02
	, KAKAO_ERRCODE)
VALUES(NEXTVAL FOR WEBDBLIB.SUREDATASEQ
		, TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')
		, 'seegene'
		, NULL
		, NULL
		, 'a6fb47772e56c22e5ae7a6cc77032498c9b44073'
		, SENDNAM
		, SENDHPN
		, NAM
		, NULL
		, C001HPN
		, NULL
		, C002MSG
		, '00000000000000'
		, TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')
		, '00000000000000'
		, '0'
		, 0
		, 'T' -- SMS : S , MMS: M
		, 0 -- MMS발송할 경우, MMSCONTENTS 테이블에 SEQNO와 데이터를 맞춰야함
		, NULL
		, 0
		, 0
			, NULL
		, 'gladmapo_001                            '
		, NULL
		, NULL
		, 'M'
		, 'L'
		, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
SET O_MSGCOD = 200 ;
END 