DROP PROCEDURE WEBOBJLIB.MWC001MCC;

CREATE PROCEDURE WEBOBJLIB.MWC001MCC
(
	  IN I_COR 		VARCHAR(3) 		-- COR
	, IN I_UID 		VARCHAR(12) 	-- 사용자 ID
	, IN I_IP		VARCHAR(30)		-- 로그인 IP
	, OUT O_MSGCOD	VARCHAR(3)		-- 메세지 코드
	, OUT O_ERRCOD	VARCHAR(10)		-- 에러 코드
	, IN I_HOS		CHAR(5)		-- 병원 코드
)
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
	--수진자 정보 관리, 중복 확인
	DECLARE CUR1  CURSOR WITH RETURN FOR 
		
	SELECT C001CHN FROM
	WEBDBLIB."MWC001M@"
	WHERE C001COR = I_COR 
	AND C001HOS = I_HOS;

		
	OPEN CUR1;
	
	SET O_MSGCOD = '200';
	SET O_ERRCOD = '';
END