--  Generate SQL 
--  Version:                   V7R4M0 190621 
--  Generated on:              22/07/04 18:31:22 
--  Relational Database:       NEODIN 
--  Standards Option:          Db2 for i 
--DROP SPECIFIC PROCEDURE IF EXISTS WEBOBJLIB.MWL001R2 ; 
--SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","NEO018" ; 
CREATE OR REPLACE PROCEDURE WEBOBJLIB.MWL001R2 ( 
  IN I_COR VARCHAR(3) , 
  IN I_UID VARCHAR(12) , 
  IN I_IP VARCHAR(30) , 
  OUT O_MSGCOD CHAR(3) , 
  OUT O_ERRCOD CHAR(10) , 
  IN I_HLK VARCHAR(50) , 
  OUT O_COR CHAR(3) , 
  OUT O_ECF CHAR(1) , 
  OUT O_UID CHAR(12) , 
  OUT O_NAM CHAR(40) , 
  OUT O_HOS CHAR(5) , 
  OUT O_AGR CHAR(20) , 
  OUT O_CDT DECIMAL(10, 0) , 
  OUT O_CTM DECIMAL(8, 0) , 
  OUT O_IYN CHAR(1) , 
  OUT O_SYN CHAR(1) , 
  OUT O_TICKER CHAR(1) , 
  OUT O_CHATBOT CHAR(1) , 
  OUT O_MONITERVIEWPRINT CHAR(1) , 
  OUT O_PAGUENHOSYN CHAR(6) ) 
  LANGUAGE SQL 
  SPECIFIC WEBOBJLIB.MWL001R2 
  NOT DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION  ALWBLK = *ALLREAD , 
  ALWCPYDTA = *OPTIMIZE , 
  COMMIT = *NONE , 
  DECRESULT = (31, 31, 00) , 
  DYNDFTCOL = *NO , 
  DYNUSRPRF = *USER , 
  SRTSEQ = *HEX 
  BEGIN	 
	 -- 병원(회원) 관리, 조회 LIST 조회 
	DECLARE V_CNT DECIMAL ( 5 , 0 ) ;  --  로그인 가능여부 확인 
	SELECT COUNT ( * ) 
	INTO V_CNT 
	FROM WEBDBLIB . MWS005M@ 
	WHERE S005COR = I_COR 
	AND S005HLK = I_HLK	 --조회ID 
	; 
	 
	IF V_CNT > 0 THEN 
		 
	 -- 병원(회원) 관리, 조회 LIST 조회 
	SELECT 
		LOGCOR 
		, USERDIV 
		, LOGLID 
		, F120FNM 
		, LOGHOS 
		, S005AGR 
		, S005CDT 
		, S005CTM 
		, S005IYN 
		, S005SYN 
		, TICKER_YN  -- 코드관리(티커 사용여부) 
, CHATBOT_YN 
		, MOINTER_VIEW_PRINT  -- 코드관리(화면출력 사용유무) 
		, PA_GUEN_HOS_YN  -- 파견사원 병원인지 확인 Flag 
	INTO O_COR , O_ECF , O_UID , O_NAM , O_HOS , O_AGR , O_CDT , O_CTM , O_IYN , O_SYN , O_TICKER , O_CHATBOT , O_MONITERVIEWPRINT , O_PAGUENHOSYN 
	FROM ( 
		SELECT TRIM ( USRCOR ) AS LOGCOR	 -- COR 
			, 'E' AS USERDIV  -- 병원, 사용자구분 
			, TRIM ( USRID ) AS LOGLID	 -- LOGIN ID 
			, TRIM ( S005AGR ) AS S005AGR	 -- 권한 
			, '' AS LOGHOS	 -- 병원코드 
			, TRIM ( F910NAM ) AS F120FNM	 -- 병원명 
			, TRIM ( S005IYN ) AS S005IYN	 -- 비밀번호초기화 여부 
			, TRIM ( S005SYN ) AS S005SYN	 -- SMS 사용 여부 
			, S005CDT 
			, S005CTM 
			, ( SELECT S002UYN FROM WEBDBLIB . MWS002M@ WHERE S002PSCD = 'TICKER_YN' AND S002RF1 = MSW005 . S005UID ) AS TICKER_YN  -- 티커(미니)사용여부 
, ( SELECT S002UYN FROM WEBDBLIB . MWS002M@ WHERE S002PSCD = 'CHATBOT_YN' AND S002RF1 = MSW005 . S005UID ) AS CHATBOT_YN  -- 티커(미니)사용여부 
			, ( SELECT S002UYN FROM WEBDBLIB . MWS002M@ WHERE S002PSCD = 'MONITER_VIEW_PRINT' AND S002RF1 = MSW005 . S005UID ) AS MOINTER_VIEW_PRINT  -- 코드관리(화면출력 사용유무) 
			, ( SELECT 
				SUBSTRING ( UPPER ( F999CD3 ) , 1 , 6 ) 
			FROM MCLISDLIB . MC999D@ 
				WHERE F999COR = I_COR 
				AND F999CD1 = 'CLIC' 
				AND F999CD2 = 'SAA2' 
				AND SUBSTRING ( UPPER ( F999CD3 ) , 1 , 6 ) = ( SELECT S005UID FROM WEBDBLIB . MWS005M@ WHERE S005HLK = I_HLK ) LIMIT 1 ) AS PA_GUEN_HOS_YN  -- 파견사원 병원인지 확인 Flag 
		FROM JMTSLIB . MMUSER@ A 
		, WEBDBLIB . MWS005M@ MSW005 
			, JMTSLIB . MM910M@ B 
		WHERE USRCOR = I_COR 
		AND B . F910COR = USRCOR 
		AND MSW005 . S005COR = A . USRCOR 
		AND USRSAB = F910SAB 
		AND S005UID = USRID 
		AND F910ODT = 0 
		AND S005HLK = I_HLK	 --조회ID 
		UNION 
		SELECT		 
			LOGCOR	 -- COR 
			, 'C' AS USERDIV  -- 병원, 사용자구분 
			, TRIM ( LOGLID ) AS LOGLID  -- LOGIN ID 
			, TRIM ( S005AGR ) AS S005AGR	 -- 권한 
			, TRIM ( LOGHOS ) AS LOGHOS  -- 병원코드 
			, TRIM ( F120FNM ) AS F120FNM  -- 병원명 
			, TRIM ( S005IYN ) AS S005IYN	 -- 비밀번호초기화 여부 
			, TRIM ( S005SYN ) AS S005SYN	 -- SMS 사용 여부 
			, S005CDT 
			, S005CTM 
			, ( SELECT S002UYN FROM WEBDBLIB . MWS002M@ WHERE S002PSCD = 'TICKER_YN' AND S002SCD = MCLOG . LOGHOS ) AS TICKER_YN  -- 티커(미니)사용여부 
, ( SELECT S002UYN FROM WEBDBLIB . MWS002M@ WHERE S002PSCD = 'CHATBOT_YN' AND S002SCD = MCLOG . LOGHOS ) AS CHATBOT_YN  -- 티커(미니)사용여부 
			, ( SELECT S002UYN FROM WEBDBLIB . MWS002M@ WHERE S002PSCD = 'MONITER_VIEW_PRINT' AND S002SCD = MCLOG . LOGHOS ) AS MOINTER_VIEW_PRINT  -- 코드관리(화면출력 사용유무) 
			, ( SELECT 
				SUBSTRING ( UPPER ( F999CD3 ) , 1 , 6 ) 
			FROM MCLISDLIB . MC999D@ 
				WHERE F999COR = I_COR 
				AND F999CD1 = 'CLIC' 
				AND F999CD2 = 'SAA2' 
				AND SUBSTRING ( UPPER ( F999CD3 ) , 1 , 6 ) = ( SELECT S005UID FROM WEBDBLIB . MWS005M@ WHERE S005HLK = I_HLK ) LIMIT 1 ) AS PA_GUEN_HOS_YN  -- 파견사원 병원인지 확인 Flag 
		FROM MCLISDLIB . MCLOGI@ MCLOG 
			, WEBDBLIB . MWS005M@ MSW005 
			, MCLISDLIB . MC120M@ M120 
		WHERE LOGCOR = I_COR 
		AND MCLOG . LOGCOR = M120 . F120COR 
		AND MCLOG . LOGHOS = M120 . F120PCD 
		AND S005COR = MCLOG . LOGCOR 
		AND S005UID = LOGLID 
		AND F120STS = 'Y' 
		AND S005HLK = I_HLK	 --조회ID 
	) AS USERTB 
	LIMIT 1 ; 
	UPDATE WEBDBLIB . MWS005M@ 
	SET S005HLK = '' 
	WHERE S005COR = I_COR 
	AND S005UID = O_UID ; 
	 
	SET O_MSGCOD = '200' ; 
	ELSE 
		SET O_MSGCOD = '340' ; 
	END IF ; 
END  ; 
