CREATE PROCEDURE WEBOBJLIB.MWC001MR1 (IN I_COR VARCHAR(3)
									  , IN I_UID VARCHAR(12)
									  , IN I_IP  VARCHAR(30)
									  , OUT O_MSGCOD VARCHAR(3)
									  , OUT O_ERRCOD VARCHAR(10)
									  , IN I_CHN  VARCHAR(2000)
									  )
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
	--sms 리스트 조회
	DECLARE CUR1 CURSOR WITH RETURN FOR
		SELECT C001COR
		  , C001HOS
		  , C001CHN
		  , C001NAM
		  , C001HPN
		  , C001BDT
		  , C001SEX
		  , C001AGE
	FROM WEBDBLIB."MWC001M@"
	WHERE (I_CHN = '' OR C001CHN IN (I_CHN));
	OPEN CUR1 ;
	SET O_ERRCOD = '' ;
	SET O_MSGCOD = 200 ;
END    