CREATE PROCEDURE WEBOBJLIB.MWR003MR (IN I_COR VARCHAR(3)
									  , IN I_UID VARCHAR(12)
									  , IN I_IP  VARCHAR(30)
									  , OUT O_MSGCOD VARCHAR(3)
									  , OUT O_ERRCOD VARCHAR(10)
									  )
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
	--redTxt GCD조회
	DECLARE CUR1 CURSOR WITH RETURN FOR
		SELECT DISTINCT R003GCD FROM WEBDBLIB."MWR003M@";
	OPEN CUR1 ;
	SET O_ERRCOD = '' ;
	SET O_MSGCOD = 200 ;
END 