CREATE PROCEDURE WEBOBJLIB.MWS013CC (IN I_COR VARCHAR(3)
									  , IN I_UID VARCHAR(12)
									  , IN I_IP  VARCHAR(30)
									  , OUT O_MSGCOD VARCHAR(3)
									  , OUT O_ERRCOD VARCHAR(10)
									  , IN I_MCD  VARCHAR(20)
									  )
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
	--도움말 중복입력 체크
	DECLARE C1 CURSOR WITH RETURN FOR
		SELECT COUNT(*) CNT  
		FROM WEBDBLIB.MWS013M@
		WHERE S013MCD = I_MCD;
	OPEN C1;
	SET O_ERRCOD = '';
	SET O_MSGCOD = 200;
END