--  Generate SQL 
--  Version:                   V7R2M0 140418 
--  Generated on:              22/02/18 09:08:20 
--  Relational Database:       NEODIN 
--  Standards Option:          DB2 for i 
DROP SPECIFIC PROCEDURE WEBOBJLIB.SEL_CMAHOMEPAGE_GETRPTTXT_SGREPT_SP_ISCN_SUM ; 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","NEO030" ; 
CREATE OR REPLACE PROCEDURE WEBOBJLIB.SEL_CMAHOMEPAGE_GETRPTTXT_SGREPT_SP_ISCN_SUM ( 
  IN $P_COR CHAR(3) , 
  IN $P_DAT DECIMAL(8, 0) , 
  IN $P_JNO DECIMAL(6, 0) , 
  IN $P_GCD CHAR(5) ) 
  DYNAMIC RESULT SETS 1 
  LANGUAGE SQL 
  SPECIFIC WEBOBJLIB.SEL_CMAHOMEPAGE_GETRPTTXT_SGREPT_SP_ISCN_SUM 
  NOT DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION  ALWBLK = *ALLREAD , 
  ALWCPYDTA = *OPTIMIZE , 
  COMMIT = *CHG , 
  DBGVIEW = *SOURCE , 
  DECRESULT = (31, 31, 00) , 
  DFTRDBCOL = *NONE , 
  DLYPRP = *NO , 
  DYNDFTCOL = *NO , 
  DYNUSRPRF = *USER , 
  SRTSEQ = *HEX 
  BEGIN 
	DECLARE CUR CURSOR FOR 
	 
WITH TAB ( ID , PROFILE ) AS 
( 
SELECT 
'1' AS ID 
--, REPLACE ( SUBSTRING ( FRPTTXT1 , LOCATE_IN_STRING ( FRPTTXT1 , '##' , 1 , 1 ) , ( LOCATE_IN_STRING ( FRPTTXT1 , '##' , 1 , 2 ) - LOCATE_IN_STRING ( FRPTTXT1 , '##' , 1 , 1 ) ) ) , CONCAT ( '##' , CHR ( 13 ) || CHR ( 10 ) ) , '' ) AS PROFILE 
, REPLACE ( REPLACE ( REPLACE ( SUBSTRING ( FRPTTXT1 , LOCATE_IN_STRING ( FRPTTXT1 , '##' , 1 , 1 ) , ( LOCATE_IN_STRING ( FRPTTXT1 , '##' , 1 , 2 ) - LOCATE_IN_STRING ( FRPTTXT1 , '##' , 1 , 1 ) ) ) , '##' , '' ) , CHR ( 13 ) , '' ) , CHR ( 10 ) , '' ) AS PROFILE 
FROM MCLISDLIB . SGREPT@ 
WHERE FRPTCOR = $P_COR 
AND FRPTDAT = $P_DAT 
AND FRPTJNO = $P_JNO 
AND FRPTGCD = $P_GCD 
) 
SELECT 
LISTAGG ( ISCN . COL1_ISCN , CHR ( 13 ) || CHR ( 10 ) ) WITHIN GROUP ( ORDER BY ISCN . COL1_ISCN ) AS ISCN_SUM 
FROM ( 
SELECT 
REPLACE ( REPLACE ( SUBSTRING ( ARR . PROFILE , 0 , LOCATE_IN_STRING ( ARR . PROFILE , '#' , 1 , 1 ) ) , CHR ( 13 ) , '' ) , CHR ( 10 ) , '' ) AS COL1_ISCN 
FROM ( 
	SELECT A . ID , B . ITEM AS PROFILE 
	FROM TAB A 
	, XMLTABLE ( '$doc/items/item' 
	PASSING XMLPARSE ( DOCUMENT CAST ( '<items><item>' || REPLACE ( A . PROFILE , '++' , '</item><item>' ) || '</item></items>' AS CLOB ) ) AS "doc" 
	COLUMNS 
	ITEM VARCHAR ( 255 ) PATH '.' 
	) B 
	WHERE B . ITEM <> '' 
) AS ARR 
INNER JOIN TAB AS T ON T . ID = ARR . ID 
) ISCN 
; 
OPEN CUR ; 
SET RESULT SETS CURSOR CUR ; 
END  ; 
