--  Generate SQL 
--  Version:                   V7R2M0 140418 
--  Generated on:              22/01/24 16:51:40 
--  Relational Database:       NEODIN 
--  Standards Option:          DB2 for i 
--DROP SPECIFIC PROCEDURE WEBOBJLIB.MO_BANKING_CM_CODE_SELECT ; 
--SET PATH "QSYS","QSYS2","YSLEE" ; 
CREATE OR REPLACE PROCEDURE WEBOBJLIB.MO_BANKING_CM_CODE_SELECT ( 
  	IN $P_COR CHAR(3) , 
  	IN $P_CM_CODE1 VARCHAR(10) , 
  	IN $P_CM_CODE2 VARCHAR(10) 
  ) 
  DYNAMIC RESULT SETS 1 
  LANGUAGE SQL 
  SPECIFIC WEBOBJLIB.MO_BANKING_CM_CODE_SELECT 
  NOT DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION  ALWBLK = *ALLREAD , 
  ALWCPYDTA = *OPTIMIZE , 
  COMMIT = *CHG , 
  DBGVIEW = *SOURCE , 
  CLOSQLCSR = *ENDACTGRP , 
  DECRESULT = (31, 31, 00) , 
  DFTRDBCOL = *NONE , 
  DLYPRP = *NO , 
  DYNDFTCOL = *NO , 
  DYNUSRPRF = *USER , 
  RDBCNNMTH = *RUW , 
  SRTSEQ = *HEX 
  BEGIN DECLARE CR_PCMCD00001 CURSOR FOR SELECT TRIM ( C . TABLE_ID_3 ) AS CODE 
,						C . DESCRIPTION_1 AS NAME ,						C . DESCRIPTION_2 AS DESC ,		C . COMPANY ,						TRIM ( C . TABLE_ID_1 ) AS TABLE_ID_1 ,						TRIM ( C . TABLE_ID_2 ) AS 
TABLE_ID_2 ,						TRIM ( C . TABLE_ID_3 ) AS TABLE_ID_3 ,						C . DISPLAY_SEQ ,						C . DESCRIPTION_1 ,						C . DESCRIPTION_2 ,						C . DESCRIPTION_3 ,						C . DESCRIPTION_4 ,						C . CRTD_DATETIME ,						CASE WHEN E1 . NAME_KOREA IS 
NULL THEN C . CRTD_BADGE ELSE TRIM ( E1 . NAME_KOREA ) END AS CRTD_BADGE ,						C . UPDT_DATETIME ,						CASE WHEN E2 . NAME_KOREA IS NULL THEN C . UPDT_BADGE ELSE TRIM ( E2 . NAME_KOREA ) END AS UPDT_BADGE			FROM XCEEDIDLIB . CM_CODE3 C LEFT JOIN XCEEDIDLIB . TB_HR_EMP E1 ON E1 . COMPANY = C . COMPANY AND E1 . BADGE = C . CRTD_BADGE LEFT JOIN XCEEDIDLIB . TB_HR_EMP E2 ON E2 . COMPANY = C . COMPANY AND E2 . BADGE = C . UPDT_BADGE WHERE C . TABLE_ID_1 = $P_CM_CODE1 AND C . TABLE_ID_2 = $P_CM_CODE2 AND C . COMPANY			= $P_COR ORDER BY C . DISPLAY_SEQ ; OPEN CR_PCMCD00001 ; SET RESULT SETS CURSOR CR_PCMCD00001 ; END  ; 
