--  Generate SQL 
--  Version:                   V7R2M0 140418 
--  Generated on:              22/07/05 08:39:11 
--  Relational Database:       NEODIN 
--  Standards Option:          DB2 for i 
--DROP SPECIFIC PROCEDURE WEBOBJLIB.MWL001R ; 
CREATE OR REPLACE PROCEDURE WEBOBJLIB.MWL001R ( 
  IN I_UID CHAR(12) , 
  IN I_IP CHAR(30) , 
  OUT O_MSGCOD CHAR(3) , 
  OUT O_ERRCOD CHAR(10) , 
  IN I_PSW CHAR(20) , 
  IN I_PSW_NXT VARCHAR(1000) , 
  OUT O_COR CHAR(3) , 
  OUT O_ECF CHAR(1) , 
  OUT O_UID CHAR(12) , 
  OUT O_NAM CHAR(40) , 
  OUT O_HOS CHAR(5) , 
  OUT O_AGR CHAR(20) , 
  OUT O_CDT DECIMAL(8, 0) , 
  OUT O_CTM DECIMAL(6, 0) , 
  OUT O_IYN CHAR(1) , 
  OUT O_SYN CHAR(1) , 
  OUT O_TICKER CHAR(1) , 
  OUT O_CHATBOT CHAR(1) , 
  OUT O_MONITERVIEWPRINT CHAR(1) , 
  OUT O_PAGUENHOSYN CHAR(6) ) 
  LANGUAGE RPGLE 
  SPECIFIC WEBOBJLIB.MWL001R 
  NOT DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  EXTERNAL NAME 'WEBOBJLIB/MWL001R' 
  PARAMETER STYLE GENERAL ; 
