DROP PROCEDURE WEBOBJLIB.MWS005D;

CREATE OR REPLACE PROCEDURE WEBOBJLIB.MWS005D
(
	  IN  I_COR 	VARCHAR(3) 	-- COR
	, IN  I_UID 	VARCHAR(12) -- 사용자 ID
	, IN  I_IP	  	VARCHAR(30)	-- 로그인 IP
	, OUT O_MSGCOD	VARCHAR(3)		-- 메세지 코드
	, OUT O_ERRCOD	VARCHAR(10)	-- 에러 코드
	, IN  I_LOGCOR	VARCHAR(3)	--	COR
	, IN  I_LOGLID	VARCHAR(12) --	LOGIN ID
	, IN  I_USERDIV	VARCHAR(12) --	사용자구분
)
BEGIN
	-- 병원(회원) 사용자 삭제
	DECLARE V_CNT DECIMAL(5,0);	-- 사용자 아이디
	DECLARE V_S002SCD VARCHAR(20);
	SET O_MSGCOD = '200';
	SET O_ERRCOD = '';


	SELECT COUNT(*) -- 사용자 아이디 체크
	INTO V_CNT
	FROM WEBDBLIB.MWS005M@
	WHERE S005COR = I_LOGCOR
	AND S005UID = I_LOGLID;
	
	-- 권한 삭제
	IF V_CNT > 0 THEN	
		DELETE FROM WEBDBLIB.MWS005M@
		WHERE S005COR = I_LOGCOR
		AND S005UID = I_LOGLID;
	ELSE
		SET O_MSGCOD = '300';
	
	END IF;	
	IF I_USERDIV = 'C' THEN
		SELECT COUNT(*) -- 사용자 아이디 체크
		INTO V_CNT
		FROM MCLISDLIB.MCPASW@T
		WHERE PASCOR = I_LOGCOR
		AND PASLID = I_LOGLID;
		
		IF V_CNT  > 0  THEN
			DELETE FROM MCLISDLIB.MCPASW@T
			WHERE PASCOR = I_LOGCOR
			AND PASLID = I_LOGLID;
		END IF;	--비밀번호 수정
	
		
		SELECT COUNT(*) -- 사용자 아이디 체크
		INTO V_CNT
		FROM MCLISDLIB.MCLOGI@
		WHERE LOGCOR = I_LOGCOR
		AND LOGLID = I_LOGLID;
			
	--MCLISDLIB.MCLOGI@ 수정
		IF V_CNT > 0 THEN
			DELETE FROM MCLISDLIB.MCLOGI@
			WHERE  LOGCOR	 =  I_LOGCOR	-- COR 
			AND LOGLID		 =  I_LOGLID	-- LOGIN ID
			;
		END IF;
	END IF;
END
