--  Generate SQL 
--  Version:                   V7R2M0 140418 
--  Generated on:              20/11/10 15:52:02 
--  Relational Database:       NEODIN 
--  Standards Option:          DB2 for i 
DROP SPECIFIC PROCEDURE WEBOBJLIB.SEL04_REPORTPRINT_A4_GENERAL_COMMON_TAIL_SP_01 ; 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","NEO014" ; 
CREATE OR REPLACE PROCEDURE WEBOBJLIB.SEL04_REPORTPRINT_A4_GENERAL_COMMON_TAIL_SP_01 ( 
  IN $P_COR CHAR(3) , 
  IN $P_DAT VARCHAR(8) , 
  IN $P_JNO VARCHAR(5) , 
  IN $P_FNO CHAR(2) ) 
  DYNAMIC RESULT SETS 2 
  LANGUAGE SQL 
  SPECIFIC WEBOBJLIB.SEL04_REPORTPRINT_A4_GENERAL_COMMON_TAIL_SP_01 
  NOT DETERMINISTIC 
  READS SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION  ALWBLK = *ALLREAD , 
  ALWCPYDTA = *OPTIMIZE , 
  COMMIT = *NONE , 
  DBGVIEW = *SOURCE , 
  DECRESULT = (31, 31, 00) , 
  DFTRDBCOL = *NONE , 
  DLYPRP = *NO , 
  DYNDFTCOL = *NO , 
  DYNUSRPRF = *USER , 
  SRTSEQ = *HEX 
  BEGIN 
--/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
--////////////////////////////////////////////// 의뢰한 센터(기존센터) /////////////////////////////////////////////////////// 
--////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
DECLARE CUR_ORDER CURSOR WITH RETURN TO CALLER FOR 
WITH TARGET_LMB AS 
( 
SELECT HOSPITAL , LMB 
FROM ( 
SELECT ROW_NUMBER ( ) OVER ( PARTITION BY HOSPITAL ORDER BY ACCESS_DATE DESC ) AS ROW_NUM , HOSPITAL , LMB 
FROM MCLISDLIB . MCHOSLMBH@ 
WHERE COMPANY = $P_COR 
AND ACCESS_DATE <= $P_DAT 
) WHERE ROW_NUM = 1 
) 
, TARGET_057 AS 
( 
SELECT F057LAB , F057HAK , F057NM1 , F057NO1 , F057NM3 , F057NO3 , F057NM5 , F057NO5 , F057NM7 , F057NO7 , F057KLM , F057ORG , F057ADR , F057TEL , F057FAX 
FROM ( 
SELECT 
ROW_NUMBER ( ) OVER ( PARTITION BY F057LAB , F057HAK ORDER BY F057OSD DESC ) AS ROW_NUM 
, F057LAB , F057HAK , F057NM1 , F057NO1 , F057NM3 , F057NO3 , F057NM5 , F057NO5 , F057NM7 , F057NO7 , F057KLM , F057ORG , F057ADR , F057TEL , F057FAX 
FROM MCLISDLIB . MC057M@ 
WHERE F057COR = $P_COR 
AND F057OSD <= $P_DAT 
GROUP BY F057LAB , F057HAK , F057OSD , F057NM1 , F057NO1 , F057NM3 , F057NO3 , F057NM5 , F057NO5 , F057NM7 , F057NO7 , F057KLM , F057ORG , F057ADR , F057TEL , F057FAX 
) WHERE ROW_NUM = 1 
) 
SELECT 
LISTAGG ( TRIM ( SALES ) , ',' ) AS SALES 
, LISTAGG ( TRIM ( COALESCE ( ORDER_CHARGE_TEST_NM , '' ) ) , ',' ) AS ORDER_CHARGE_TEST_NM 
, LISTAGG ( TRIM ( COALESCE ( ORDER_CHARGE_TEST_NO , '' ) ) , ',' ) AS ORDER_CHARGE_TEST_NO 
, LISTAGG ( TRIM ( COALESCE ( ORDER_CHARGE_DR_NM , '' ) ) , ',' ) AS ORDER_CHARGE_DR_NM 
, LISTAGG ( TRIM ( COALESCE ( ORDER_CHARGE_DR_NO , '' ) ) , ',' ) AS ORDER_CHARGE_DR_NO 
, LISTAGG ( TRIM ( COALESCE ( ORDER_CONFIRM_DR_NM , '' ) ) , ',' ) AS ORDER_CONFIRM_DR_NM 
, LISTAGG ( TRIM ( COALESCE ( ORDER_CONFIRM_DR_NO , '' ) ) , ',' ) AS ORDER_CONFIRM_DR_NO 
, LISTAGG ( TRIM ( COALESCE ( ORDER_DIRECTOR_DR_NM , '' ) ) , ',' ) AS ORDER_DIRECTOR_DR_NM 
, LISTAGG ( TRIM ( COALESCE ( ORDER_DIRECTOR_DR_NO , '' ) ) , ',' ) AS ORDER_DIRECTOR_DR_NO 
, LISTAGG ( TRIM ( COALESCE ( ORDER_CENTER_INFO , '' ) ) , ',' ) AS ORDER_CENTER_INFO 
FROM ( 
SELECT DISTINCT 
SALES . F910NAM AS SALES 
, CASE WHEN ORDER_CENTER . F057LAB IS NULL THEN ORDER_CENTER_0000 . F057NM1 ELSE ORDER_CENTER . F057NM1 END AS ORDER_CHARGE_TEST_NM 
, CASE WHEN ORDER_CENTER . F057LAB IS NULL THEN ORDER_CENTER_0000 . F057NO1 ELSE ORDER_CENTER . F057NO1 END AS ORDER_CHARGE_TEST_NO 
, CASE WHEN ORDER_CENTER . F057LAB IS NULL THEN ORDER_CENTER_0000 . F057NM3 ELSE ORDER_CENTER . F057NM3 END AS ORDER_CHARGE_DR_NM 
, CASE WHEN ORDER_CENTER . F057LAB IS NULL THEN ORDER_CENTER_0000 . F057NO3 ELSE ORDER_CENTER . F057NO3 END AS ORDER_CHARGE_DR_NO 
, CASE WHEN ORDER_CENTER . F057LAB IS NULL THEN ORDER_CENTER_0000 . F057NM5 ELSE ORDER_CENTER . F057NM5 END AS ORDER_CONFIRM_DR_NM 
, CASE WHEN ORDER_CENTER . F057LAB IS NULL THEN ORDER_CENTER_0000 . F057NO5 ELSE ORDER_CENTER . F057NO5 END AS ORDER_CONFIRM_DR_NO 
, CASE WHEN ORDER_CENTER . F057LAB IS NULL THEN ORDER_CENTER_0000 . F057NM7 ELSE ORDER_CENTER . F057NM7 END AS ORDER_DIRECTOR_DR_NM 
, CASE WHEN ORDER_CENTER . F057LAB IS NULL THEN ORDER_CENTER_0000 . F057NO7 ELSE ORDER_CENTER . F057NO7 END AS ORDER_DIRECTOR_DR_NO 
, CASE WHEN ORDER_CENTER . F057LAB IS NULL THEN TRIM ( ORDER_CENTER_0000 . F057KLM ) || ' | ' || TRIM ( ORDER_CENTER_0000 . F057ORG ) || ' | ' || TRIM ( ORDER_CENTER_0000 . F057ADR ) || ' | ' || TRIM ( ORDER_CENTER_0000 . F057TEL ) || ' | ' || TRIM ( ORDER_CENTER_0000 . F057FAX ) 
ELSE TRIM ( ORDER_CENTER . F057KLM ) || ' | ' || TRIM ( ORDER_CENTER . F057ORG ) || ' | ' || TRIM ( ORDER_CENTER . F057ADR ) || ' | ' || TRIM ( ORDER_CENTER . F057TEL ) || ' | ' || TRIM ( ORDER_CENTER . F057FAX ) END AS ORDER_CENTER_INFO 
FROM MCLISDLIB . MC100H@ 
INNER JOIN MCLISDLIB . MC600M@ 
ON F100COR = F600COR 
AND F100DAT = F600DAT 
AND F100JNO = F600JNO 
INNER JOIN JMTSLIB . MM910M@ AS SALES 
ON F910COR = F100COR 
AND F910SAB = F100MBC 
INNER JOIN TARGET_LMB 
ON F100HOS = HOSPITAL 
LEFT JOIN TARGET_057 AS ORDER_CENTER 
ON ORDER_CENTER . F057LAB = LMB 
AND ORDER_CENTER . F057HAK = F600HAK 
LEFT JOIN TARGET_057 AS ORDER_CENTER_0000 
ON ORDER_CENTER_0000 . F057LAB = LMB 
AND ORDER_CENTER_0000 . F057HAK = '0000' 
WHERE F100COR = $P_COR 
AND F100DAT = $P_DAT 
AND F100JNO = $P_JNO 
AND ( ORDER_CENTER . F057LAB IS NOT NULL OR ORDER_CENTER_0000 . F057LAB IS NOT NULL ) 
AND F600C03 = 'Y' 
) AS GROUPING_DATA 
; 
OPEN CUR_ORDER ; 
END  ; 
