DROP PROCEDURE WEBOBJLIB.MWH001R2;

CREATE PROCEDURE WEBOBJLIB.MWH001R2
(
	  IN I_COR 		VARCHAR(3) 	-- COR
	, IN I_UID 		VARCHAR(12) -- 사용자 ID
	, IN I_IP	  	VARCHAR(30)	-- 로그인 IP
	, OUT O_MSGCOD	CHAR(3)		-- 메세지 코드
	, OUT O_ERRCOD	CHAR(10)	-- 에러 코드
	, IN I_MBC 	VARCHAR(6) -- 사번
)
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN	
	IF I_MBC = '' THEN 
		BEGIN	
			-- 담당자별 병원 관리, 상세 조회 LIST 조회
		   DECLARE CUR1  CURSOR WITH RETURN FOR  
			SELECT TRIM(F120PCD) AS F120PCD
				, TRIM(F120FNM) AS F120FNM
				, TRIM(F120TEL) AS F120TEL
			FROM MCLISDLIB.MC120M@  
			WHERE F120COR = I_COR
			AND (I_MBC != '' AND F120MBC = I_MBC)
			ORDER BY F120COR,F120PCD,F120FNM;
			OPEN CUR1;
		END;
	ELSE 
		BEGIN	
			-- 담당자별 병원 관리, 상세 조회 LIST 조회
		   DECLARE CUR2  CURSOR WITH RETURN FOR  
			SELECT TRIM(F120PCD) AS F120PCD
				, TRIM(F120FNM) AS F120FNM
				, TRIM(F120TEL) AS F120TEL
			FROM MCLISDLIB.MC120M@  
			WHERE F120COR = I_COR
			AND F120MBC = I_MBC
			ORDER BY F120COR,F120PCD,F120FNM;
			OPEN CUR2;
		END;
	END IF;
	SET O_MSGCOD = '200';

END
