CREATE PROCEDURE WEBOBJLIB.MWS015MS1 (
							 IN I_COR     VARCHAR(3)
                           , IN I_UID     VARCHAR(12)
                           , IN I_IP      VARCHAR(30)
                           , OUT O_MSGCOD VARCHAR(3)
                           , OUT O_ERRCOD VARCHAR(10)
)
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
   DECLARE C1 CURSOR WITH RETURN FOR 
      SELECT NEXTVAL FOR WEBDBLIB.MWS015MSEQ S015SEQ FROM SYSIBM.SYSDUMMY1;
   SET O_MSGCOD = 200;
   OPEN C1;
END