--  Generate SQL 
--  Version:                   V7R2M0 140418 
--  Generated on:              22/01/06 09:12:19 
--  Relational Database:       NEODIN 
--  Standards Option:          DB2 for i 
--DROP SPECIFIC PROCEDURE WEBOBJLIB.SEL_DID_USER ; 
--SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","NEO018" ; 
CREATE OR REPLACE PROCEDURE WEBOBJLIB.SEL_DID_USER ( 
  IN $I_GIC VARCHAR(8) , 
  IN $I_BDT_FROM DECIMAL(8, 0) , 
  IN $I_BDT_TO DECIMAL(8, 0) , 
  IN $I_CD2 VARCHAR(4) ) 
  DYNAMIC RESULT SETS 1 
  LANGUAGE SQL 
  SPECIFIC WEBOBJLIB.SEL_DID_USER 
  NOT DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION  ALWBLK = *ALLREAD , 
  ALWCPYDTA = *OPTIMIZE , 
  COMMIT = *NONE , 
  DECRESULT = (31, 31, 00) , 
  DYNDFTCOL = *NO , 
  DYNUSRPRF = *USER , 
  SRTSEQ = *HEX 
  BEGIN 
	DECLARE CUR1 CURSOR FOR 
		SELECT T . F600DAT						 --접수일자 
				, T . F600JNO					 --접수번호 
				, T . F600HOS					 --병원코드 
				, T . F600BDT					 --보고일자 
				, H . F100NAM					 --환자명 
				, H . F100SEX					 --성별 
				, H . F100BDT					 --생년월일 
				, COALESCE ( S . S100PCD , '' )	AS S100PCD  --국가구분코드 
				, COALESCE ( S . S100PNO , '' )	AS S100PNO  --전화번호
				-- 2022.01.06 복호화 제거
				--, ECHELON . PI_DECSN ( H . F100JN1 ) AS F100JN1  --주민번호앞자리 
				, H . F100JN1 AS F100JN1  --주민번호앞자리
		FROM MCLISDLIB . MC600M@ AS T 
		LEFT JOIN MCLISDLIB . MC100H@ AS H 
				ON F600COR = F100COR 
				AND F600DAT = F100DAT 
				AND F600JNO = F100JNO 
		LEFT JOIN MCLISDLIB . MC100HSUB@ AS S 
				ON F600COR = S100COR 
				AND F600DAT = S100DAT 
				AND F600JNO = S100JNO 
		WHERE T . F600COR = 'NML' 
		AND T . F600HOS IN ( SELECT F120PCD 
							FROM MCLISDLIB . MC120M@ 
							WHERE F120COR = 'NML' 
							AND F120GIC = $I_GIC ) 
		AND T . F600BDT BETWEEN $I_BDT_FROM AND $I_BDT_TO 
		AND T . F600GCD IN ( SELECT DISTINCT F999CD3 
							FROM MCLISDLIB . "MC999D@" 
							WHERE F999COR = 'NML' 
							AND F999CD1 = 'CLIC' 
							AND F999CD2 = $I_CD2 ) 
		AND ( TRIM ( T . F600ACD ) = '' OR T . F600ACD = '01' )  --부속코드 없거나 01 
		; 
	OPEN CUR1 ; 
	SET RESULT SETS CURSOR CUR1 ; 
END  ; 
