CREATE PROCEDURE WEBOBJLIB.MWS015DR(
									IN  I_COR    VARCHAR(3)
								  , IN  I_UID    VARCHAR(12)
								  , IN  I_IP   	 VARCHAR(30)
     							  , OUT O_MSGCOD VARCHAR(3)
   								  , OUT O_ERRCOD VARCHAR(10)
   								  , IN  I_SEQ 	 DECIMAL(11,0))
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
   DECLARE C1 CURSOR WITH RETURN FOR
   SELECT
      S015SEQ,
      S015FPT,
      S015FNM,
      S015FSNM,
      S015FSQ
   FROM WEBDBLIB."MWS015D@"
   WHERE S015SEQ = I_SEQ
   ORDER BY S015FSQ ASC;
   SET O_MSGCOD = 200 ;
   OPEN C1 ;
END