CREATE PROCEDURE WEBOBJLIB.MWS013D (IN I_COR VARCHAR(3)
									  , IN I_UID VARCHAR(12)
									  , IN I_IP  VARCHAR(30)
									  , OUT O_MSGCOD VARCHAR(3)
									  , OUT O_ERRCOD VARCHAR(10)
									  , IN I_MCD  VARCHAR(20)
									  )
BEGIN
	-- 도움말 삭제
		DELETE FROM WEBDBLIB.MWS013M@
		WHERE S013COR = I_COR
		AND S013MCD = I_MCD;
	SET O_ERRCOD = '';
	SET O_MSGCOD = 200;
END