DROP PROCEDURE WEBOBJLIB.MWC001MD;

CREATE PROCEDURE WEBOBJLIB.MWC001MD
(
	  IN I_COR 		VARCHAR(3) 		-- COR
	, IN I_UID 		VARCHAR(12) 	-- 사용자 ID
	, IN I_IP		VARCHAR(30)		-- 로그인 IP
	, OUT O_MSGCOD	VARCHAR(3)		-- 메세지 코드
	, OUT O_ERRCOD	VARCHAR(10)		-- 에러 코드
	, IN I_HOS		CHAR(5)		-- 병원 코드
	, IN I_CHN		VARCHAR(15)		-- 차트번호
)
BEGIN
	DELETE FROM WEBDBLIB.MWC001M@
	WHERE C001COR = I_COR
	AND C001HOS = I_HOS
	AND C001CHN = I_CHN;

	SET O_MSGCOD = '200';
	SET O_ERRCOD = '';
END