--  Generate SQL 
--  Version:                   V7R2M0 140418 
--  Generated on:              22/06/27 08:42:16 
--  Relational Database:       NEODIN 
--  Standards Option:          DB2 for i 
--DROP SPECIFIC PROCEDURE WEBOBJLIB.MWL001R2_CHATBOT_LOGIN_CHECK ; 
--SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","NEO018" ; 
CREATE OR REPLACE PROCEDURE WEBOBJLIB.MWL001R2_CHATBOT_LOGIN_CHECK ( 
	  IN I_UID VARCHAR(12) , 
	  IN I_HCK VARCHAR(50) , 
	  OUT O_LOGIN_CHECK CHAR(1) , 
	  OUT O_HOS_NM VARCHAR(40) , 
	  OUT O_HOS_GIC VARCHAR(8) , 
	  OUT O_HOS_DRN VARCHAR(12) , 
	  OUT O_HOS_TEL VARCHAR(20) , 
	  OUT O_HOS_HCD VARCHAR(20) , 
	  OUT O_HOS_DPT VARCHAR(4) , 
	  OUT O_HOS_DPT_NM VARCHAR(50) , 
	  OUT O_HOS_CVL VARCHAR(4) , 
	  OUT O_HOS_CVL_NM VARCHAR(50) 
  ) 
  LANGUAGE SQL 
  SPECIFIC WEBOBJLIB.MWL001R2_CHATBOT_LOGIN_CHECK 
  NOT DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION  ALWBLK = *ALLREAD , 
  ALWCPYDTA = *OPTIMIZE , 
  COMMIT = *NONE , 
  DECRESULT = (31, 31, 00) , 
  DYNDFTCOL = *NO , 
  DYNUSRPRF = *USER , 
  SRTSEQ = *HEX 
  BEGIN	 
	DECLARE V_CNT DECIMAL ( 5 , 0 ) DEFAULT 0 ;	 --  로그인 가능여부 확인 
	DECLARE HOS_NM VARCHAR ( 40 ) DEFAULT '' ;	 --  병원명 (병원인경우만 해당) 
	DECLARE HOS_GIC VARCHAR ( 8 ) DEFAULT '' ;	 --  요양기관코드 (병원인경우만 해당) 
	DECLARE HOS_DRN VARCHAR ( 12 ) DEFAULT '' ;	 -- 원장명 (병원인경우만 해당) 
	DECLARE HOS_TEL VARCHAR ( 20 ) DEFAULT '' ;	 --  병원연락처 (병원인경우만 해당) 
	DECLARE HOS_HCD VARCHAR ( 5 ) DEFAULT '' ;	 --  병원코드 (병원인경우만 해당) 
	DECLARE HOS_DPT VARCHAR ( 4 ) DEFAULT '' ;	 --  지점코드(병원인경우만 해당) 
	DECLARE HOS_DPT_NM VARCHAR ( 50 ) DEFAULT '' ;  --  지점명 (병원인경우만 해당) 
	DECLARE HOS_CVL VARCHAR ( 4 ) DEFAULT '' ;	 --  LMB코드(병원인경우만 해당) 
	DECLARE HOS_CVL_NM VARCHAR ( 50 ) DEFAULT '' ;  --  LMB명 (병원인경우만 해당)
	 
	-- 로그인한 아이디가 존재하는지 확인한다. 
	SELECT COUNT ( * ) INTO V_CNT 
	FROM WEBDBLIB . MWS005M@ 
	WHERE S005COR = 'NML' 
	AND S005UID = UPPER ( I_UID )		 --조회 ID 
	AND S005HCK = I_HCK ;			 --조회 HCK (로그인 체크 key) 
	SELECT 
		( CASE WHEN CC . F120FNM IS NULL THEN '' ELSE CC . F120FNM END ) 
		, ( CASE WHEN CC . F120GIC IS NULL THEN '' ELSE CC . F120GIC END ) 
		, ( CASE WHEN CC . F120DRN IS NULL THEN '' ELSE CC . F120DRN END ) 
		, ( SELECT LOGTEL 
			FROM MCLISDLIB . MCLOGI@ 
			WHERE LOGCOR = 'NML' 
			AND LOGLID = I_UID ) 
		, ( CASE WHEN CC . F120PCD IS NULL THEN '' ELSE CC . F120PCD END ) 
		, ( CASE WHEN CC . F120DPT IS NULL THEN '' ELSE CC . F120DPT END )  -- 지점코드 
		, ( SELECT ( CASE WHEN DD . F900KNM IS NULL THEN '' ELSE DD . F900KNM END ) FROM JMTSLIB . "MM900M@" DD 
			WHERE 1 = 1 
			AND DD . F900COR = 'NML' 
			AND DD . F900DPT = CC . F120DPT )  -- 지점명 
		, ( CASE WHEN CC . F120CVL IS NULL THEN '' ELSE CC . F120CVL END )  -- LMB코드 
		, ( SELECT ( CASE WHEN EE . F900KNM IS NULL THEN '' ELSE EE . F900KNM END ) FROM JMTSLIB . "MM900M@" EE 
	WHERE 1 = 1 
	AND EE . F900COR = 'NML' 
	AND EE . F900DPT = CC . F120CVL )  -- LMB명 
	INTO HOS_NM , HOS_GIC , HOS_DRN , HOS_TEL , HOS_HCD , HOS_DPT , HOS_DPT_NM , HOS_CVL , HOS_CVL_NM 
	FROM WEBDBLIB . MWS005M@ AA 
		LEFT JOIN MCLISDLIB . MCLOGI@ BB 
		ON AA . S005COR = BB . LOGCOR 
		AND AA . S005UID = BB . LOGLID 
		LEFT JOIN MCLISDLIB . MC120M@ CC 
		ON BB . LOGCOR = CC . F120COR 
		AND BB . LOGHOS = CC . F120PCD 
	WHERE S005COR = 'NML' 
	AND S005UID = UPPER ( I_UID ) 
	AND S005HCK = I_HCK ; 
	 
	SET O_HOS_NM = HOS_NM ; 
	SET O_HOS_GIC = HOS_GIC ; 
	SET O_HOS_DRN = HOS_DRN ; 
	SET O_HOS_TEL = HOS_TEL ; 
	SET O_HOS_HCD = HOS_HCD ; 
	SET O_HOS_DPT = HOS_DPT ; 
	SET O_HOS_DPT_NM = HOS_DPT_NM ; 
	SET O_HOS_CVL = HOS_CVL ; 
	SET O_HOS_CVL_NM = HOS_CVL_NM ; 
	 
	IF V_CNT > 0 THEN 
		 
		UPDATE WEBDBLIB . MWS005M@ 
		SET S005HCK = '' 
		WHERE S005COR = 'NML' 
		AND S005UID = UPPER ( I_UID ) 
		AND S005HCK = I_HCK ; 
		 
		SET O_LOGIN_CHECK = 'Y' ; 
	ELSE 
		SET O_LOGIN_CHECK = 'N' ; 
	END IF ; 
END  ; 
