CREATE PROCEDURE WEBOBJLIB.MWS013C (IN I_COR VARCHAR(3)
									  , IN I_UID VARCHAR(12)
									  , IN I_IP  VARCHAR(30)
									  , OUT O_MSGCOD VARCHAR(3)
									  , OUT O_ERRCOD VARCHAR(10)
									  , IN I_MCD  VARCHAR(20)
									  , IN I_CON  CLOB
									  )
BEGIN
	--도움말 입력
	INSERT INTO WEBDBLIB."MWS013M@"
	(S013COR, S013MCD, S013CON, S013CUR, S013CDT, S013CTM, S013CIP, S013UUR, S013UDT, S013UTM, S013UIP)
	VALUES('NML', I_MCD, I_CON, I_UID, TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD'), TO_CHAR(CURRENT_TIMESTAMP, 'hh24miss'), '', '', 0, 0, '');
	SET O_ERRCOD = '';
	SET O_MSGCOD = 200;
END