--  Generate SQL 
--  Version:                   V7R2M0 140418 
--  Generated on:              22/01/26 09:56:21 
--  Relational Database:       NEODIN 
--  Standards Option:          DB2 for i 
--DROP SPECIFIC PROCEDURE WEBOBJLIB.MO_BANK_INSPECTION2_SIMPLE_LIST ; 
--SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","NEO021" ; 
CREATE OR REPLACE PROCEDURE WEBOBJLIB.MO_BANK_INSPECTION2_SIMPLE_LIST ( 
  IN $P_COMPANY CHAR(3) , 
  IN $P_GCD VARCHAR(10) ) 
  DYNAMIC RESULT SETS 1 
  LANGUAGE SQL 
  SPECIFIC WEBOBJLIB.MO_BANK_INSPECTION2_SIMPLE_LIST 
  NOT DETERMINISTIC 
  MODIFIES SQL DATA 
  CALLED ON NULL INPUT 
  SET OPTION  ALWBLK = *ALLREAD , 
  ALWCPYDTA = *OPTIMIZE , 
  COMMIT = *NONE , 
  DECRESULT = (31, 31, 00) , 
  DYNDFTCOL = *NO , 
  DYNUSRPRF = *USER , 
  SRTSEQ = *HEX 
  BEGIN 
DECLARE CR_BANK_INSPECTION2_SIMPLE_LIST CURSOR FOR 
SELECT A . F010GCD AS GCD  -- 검사코드 
, TRIM ( A . F010FKN ) AS FNM  -- 검사명 
, TRIM ( A . F010SNM ) AS SNM  -- 검사명 약어 
, TRIM ( B . F011ACD ) AS ACD  -- 검사코드 
, TRIM ( B . F011ACD ) || '. ' || TRIM ( B . F011FKN ) AS ACDFNM  -- 검사명 
, TRIM ( B . F011ACD ) || '. ' || TRIM ( B . F011SNM ) AS ACDSNM  -- 검사명 약어 
FROM MCLISDLIB . MC010M@ A 
INNER JOIN MCLISDLIB . MC011M@ B 
ON B . F011COR = A . F010COR 
AND B . F011GCD = A . F010GCD 
AND B . F011ACD <> '00' 
WHERE A . F010COR = $P_COMPANY 
AND A . F010GCD = $P_GCD 
ORDER BY B . F011ACD ; 
OPEN CR_BANK_INSPECTION2_SIMPLE_LIST ; 
SET 
RESULT SETS CURSOR CR_BANK_INSPECTION2_SIMPLE_LIST ; 
END  ; 
