DROP PROCEDURE WEBOBJLIB.MWS011D;

CREATE PROCEDURE WEBOBJLIB.MWS011D
(
	  IN  I_COR 	VARCHAR(3) 	-- COR
	, IN  I_UID 	VARCHAR(12) -- 사용자 ID
	, IN  I_IP	  	VARCHAR(30)	-- 로그인 IP
	, OUT O_MSGCOD	VARCHAR(3)		-- 메세지 코드
	, OUT O_ERRCOD	VARCHAR(10)	-- 에러 코드
	, IN  I_RFM		VARCHAR(20 )		   -- 폼
)
BEGIN
	-- 폼별 결과 양식 관리 삭제
	SET O_MSGCOD = '200';
	SET O_ERRCOD = '';
	DELETE FROM WEBDBLIB.MWS011M@
	   WHERE S011COR = I_COR
	   AND S011RFM = I_RFM	--폼
	;
END
