DROP PROCEDURE WEBOBJLIB.MWS007CC;

CREATE  PROCEDURE WEBOBJLIB.MWS007CC
(
	  IN I_COR 		VARCHAR(3) 	-- COR
	, IN I_UID 		VARCHAR(12) -- 사용자 ID
	, IN I_IP	  	VARCHAR(30)	-- 로그인 IP
	, OUT O_MSGCOD	CHAR(3)		-- 메세지 코드
	, OUT O_ERRCOD	CHAR(10)	-- 에러 코드
	, IN I_MCD 	VARCHAR(20) -- 사번
	, IN I_RCD 	VARCHAR(20) -- 검색어코드
)
BEGIN	
	-- Quick Setup 중복확인
	DECLARE V_CNT DECIMAL(5,0);	--  수량 확인

   SELECT  COUNT(*)
    INTO  V_CNT
	FROM WEBDBLIB.MWS007M@
	WHERE S007COR = I_COR
	AND S007MCD = I_MCD
	AND S007RCD = I_RCD;
   
   IF V_CNT >0 THEN
	SET O_MSGCOD = '202';
   ELSE
	SET O_MSGCOD = '200';
   END IF;

END



