DROP PROCEDURE WEBOBJLIB.MWC003MD;

CREATE PROCEDURE WEBOBJLIB.MWC003MD
(
	  IN I_COR 		VARCHAR(3) 		-- 회사 코드
	, IN I_UID 		VARCHAR(12) 	-- 사용자 ID
	, IN I_IP		VARCHAR(30)		-- 로그인 IP
	, OUT O_MSGCOD	VARCHAR(3)		-- 메세지 코드
	, OUT O_ERRCOD	VARCHAR(10)		-- 에러 코드
	, IN I_HOS		CHAR(5)			-- 병원 코드
	, IN I_GCD		CHAR(5)			-- 검사항목 코드
	, IN I_SEQ		DECIMAL(10, 0)	-- 메시지 순번
)
BEGIN
	-- SMS 연동관리, 메시지 삭제
	DELETE FROM WEBDBLIB.MWC003D@
	WHERE C003COR = I_COR
	AND C003HOS = I_HOS
	AND C003SEQ = I_SEQ;

	DELETE FROM WEBDBLIB.MWC003M@
	WHERE C003COR = I_COR
	AND C003HOS = I_HOS
	AND C003GCD = I_GCD
	AND C003SEQ = I_SEQ;

	SET O_MSGCOD = '200';
	SET O_ERRCOD = '';

END