var gridRowHeight = 32;

function setStyles(grid){
	grid.setStyles(basicGrayBlueSkin);
	
	grid.setStyles({
        header: {
        	fontSize: "12"  //헤더의 폰트 크기
//        	,fontFamily:"맑은 고딕, 돋움, 굴림"
        },
		body: {
			fontSize: "13"  //그리드 상세 폰트 크기 
//	        , fontFamily:"맑은 고딕, 돋움, 굴림"
		}
    });
	//"맑은 고딕", 돋움, 굴림;
	
	/* 
	 * 그리드 스타일 참고 페이지 
	 * http://demo.realgrid.com/GridStyle/StyleProperties/
	 * http://help.realgrid.com/tutorial/a28/
	 * */
	
	
	/*높이 설정*/
//	grid.setHeader ( {height: 30});
	/*높이 설정*/
	
	/* 설정 */
	grid.setOptions({
		panel : { visible : false },
		footer: { visible : false }
	});
	grid.setEditOptions({
    	editable : false
    });
//	grid.setSelectOptions({
//		  style: 'singleRow'
//		});
	grid.setDisplayOptions({
		/*even : 표시할 컬럼들의 전체 너비가 그리드 너비보다 작은 경우 남는 크기를 각 컬럼에 고르게 분배한다. 표시할 컬럼들의 전체 너비가 그리드 너비보다 큰 경우에는 크기 변동이 없다.*/
		fitStyle: "even"
		/*선택내역 색상*/
		, rowFocusVisible:true 
		, rowFocusBackground:"#34FFA120"
		/*선택내역 색상 설정*/
		/*조회 되기 전 보이는 내역 */
    	, showEmptyMessage : true
    	, emptyMessage : "조회된 자료가 없습니다"
		/*조회 되기 전 보이는 내역 */
		/*Row 높이*/
		, rowHeight: gridRowHeight
		/*로우 호버  설정*/
		, rowHoverMask:{
			visible:true,
				styles:{
					background:"#3264AAFF"
				},
			hoverMask: "row"
		}
	});
	TabResize();
}

/**
 * setGridBar(grid, 보이는 상태, type)
 * CheckBar,StateBar 제거 - setGridBar(grid, false);
 * CheckBar 제거 - setGridBar(grid, false,"check");
 * setStateBar 제거 - setGridBar(grid, false,"state");
 * **/
function setGridBar(grid, visib, type){
    var options = { visible: visib};
    if(isNull(type)){
    	grid.setCheckBar(options);
        grid.setStateBar(options);
    }
    if(type=="check"){
    	grid.setCheckBar(options);
    }
    if(type=="state"){
    	grid.setStateBar(options);
    }
}

	//!basic-grayBlue	
var basicGrayBlueSkin =
	{"grid": {"background":"#ffffffff"
			,"iconLocation":"left"
			,"border":"#d9d9d9,1"
			,"iconAlignment":"center"
			,"borderBottom":"#a9a9a9,1"
			,"fontFamily":"맑은 고딕"
			,"iconPadding":"0"
			,"selectedBackground":"#ff696969"
			,"contentFit":"auto"
			,"inactiveBackground":"#ffd3d3d3"
			,"iconOffset":"0"
			,"selectionDisplay":"mask"
			,"hoveredMaskBackground":"#ffff7000"
			,"hoveredMaskBorder":"#ffff0000,1"
			,"paddingRight":"2"
			,"paddingBottom":"2"
			,"paddingTop":"2"
			,"figureBackground":"#ff657082"
			,"selectedForeground":"#ffffffff"
			,"foreground":"#ff000000"
			,"inactiveForeground":"#ff808080"
			,"line":"#ffb7bdc7,1"
			,"textAlignment":"center"
			,"lineAlignment":"center"
			,"iconIndex":"0"}
	,"panel":{"background":"#ffa4a8b1"
			,"paddingRight":"2"
			,"iconLocation":"left"
			,"border":"#a9a9a9,1"
			,"selectedForeground":"#ffffffff"
			,"iconAlignment":"center"
			,"foreground":"#ffffffff"
			,"inactiveForeground":"#ff808080"
			,"borderBottom":"#a9a9a9,1"
			,"textAlignment":"near"
			,"selectedBackground":"#ff696969"
			,"lineAlignment":"center"
			,"inactiveBackground":"#ffd3d3d3"
			,"iconOffset":"0"
			,"selectionDisplay":"mask"
			,"hoveredMaskBorder":"#335292f7,1"
			,"iconPadding":"0"
			,"hoveredMaskBackground":"#1f5292f7"
			,"contentFit":"auto"
			,"paddingTop":"4"
			,"borderRight":"#a9a9a9,1"
			,"figureBackground":"#ff008800"
			,"paddingBottom":"5"
			,"iconIndex":"0"}
	,"body":{"background":"#ffffffff"
			,"iconLocation":"left"
			,"border":"#ffffffff,0"
			,"iconAlignment":"center"
			,"borderBottom":"#a9a9a9,1"
			,"fontFamily":"맑은 고딕"
			,"borderTop":"#ffffffff,0"
			,"selectedBackground":"#ff696969"
			,"contentFit":"auto"
			,"inactiveBackground":"#ffd3d3d3"
			,"iconOffset":"0"
			,"fontSize":"12"
			,"selectionDisplay":"mask"
			,"iconPadding":"0"
			,"hoveredMaskBackground":"#1f5292f7"
			,"hoveredMaskBorder":"#335292f7,1"
			,"figureBackground":"#ff008800"
			,"paddingBottom":"2"
			,"paddingTop":"2"
			,"paddingRight":"2"
			,"paddingLeft":"2"
			,"selectedForeground":"#ffffffff"
			,"foreground":"#ff222530"
			,"inactiveForeground":"#ff808080"
			,"line":"#ff808080,1"
			,"textAlignment":"near"
			,"borderLeft":"#ffffffff,0"
			,"lineAlignment":"center"
			,"borderRight":"#a9a9a9,1"
			,"iconIndex":"0"
			,"empty":{}}
	,"fixed":{"background":"#ffd3d3d3"
			,"iconLocation":"left"
			,"border":"#a9a9a9,1"
			,"iconAlignment":"center"
			,"borderBottom":"#a9a9a9,1"
			,"fontFamily":"맑은 고딕"
			,"iconPadding":"0"
			,"selectedBackground":"#ff696969"
			,"contentFit":"auto"
			,"inactiveBackground":"#ffd3d3d3"
			,"iconOffset":"0"
			,"selectionDisplay":"mask"
			,"hoveredMaskBackground":"#1f5292f7"
			,"hoveredMaskBorder":"#335292f7,1"
			,"paddingRight":"2"
			,"paddingBottom":"2"
			,"paddingTop":"2"
			,"figureBackground":"#ff008800"
			,"selectedForeground":"#ffffffff"
			,"foreground":"#ff000000"
			,"inactiveForeground":"#ff808080"
			,"textAlignment":"center"
			,"lineAlignment":"center"
			,"borderRight":"#a9a9a9,1"
			,"iconIndex":"0"
			,"colBar":{"background":"#ffffffff"
				,"iconLocation":"left"
				,"border":"#a9a9a9,1"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"fontFamily":"맑은 고딕"
				,"iconPadding":"0"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"hoveredMaskBackground":"#ffff7000"
				,"hoveredMaskBorder":"#ffff0000,1"
				,"paddingRight":"2"
				,"paddingBottom":"2"
				,"paddingTop":"2"
				,"figureBackground":"#ff008800"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff000000"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"center"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			,"rowBar":{"background":"#ffd3d3d3"
				,"iconLocation":"left"
				,"border":"#a9a9a9,1"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"fontFamily":"맑은 고딕"
				,"iconPadding":"0"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"hoveredMaskBackground":"#1f5292f7"
				,"hoveredMaskBorder":"#335292f7,1"
				,"paddingRight":"2"
				,"paddingBottom":"2"
				,"paddingTop":"2"
				,"figureBackground":"#ff008800"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff000000"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"center"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			}
	,"header":{"background":"linear,#fafafa,#d9d9d9,90"
//	,"header":{"background":"linear,#fafafa,#fafafa,90"
			,"iconLocation":"left"
			,"border":"#ffffffff,0"
			,"iconAlignment":"center"
			,"borderBottom":"#a9a9a9,1"
			,"fontFamily":"돋움"//#c7171d
			,"borderTop":"#c7171d,0"
			,"selectedBackground":"linear,#ffcad0d7,#ffb7bec7,90"
			,"contentFit":"auto"
			,"inactiveBackground":"#ffd3d3d3"
			,"iconOffset":"0"
			,"selectionDisplay":"mask"
			,"iconPadding":"0"
			,"hoveredMaskBackground":"#22002b5b"
			,"fontBold":"true"
			,"figureBackground":"#ff008800"
			,"paddingTop":"8"
			,"paddingBottom":"8"
			,"hoveredMaskBorder":"#ffff0000,1"
			,"paddingRight":"2"
			,"selectedForeground":"#ff000000"
			,"foreground":"#ff222530"
			,"inactiveForeground":"#ff808080"
			,"textAlignment":"center"
			,"borderLeft":"#ffffffff,0"
			,"lineAlignment":"center"
			,"borderRight":"#a9a9a9,1"
			,"iconIndex":"0"
			,"group":{"background":"linear,#ffffffff,#ffe7e8eb,90"
				,"iconLocation":"left"
				,"border":"#ffffffff,0"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"borderTop":"#c7171d,0"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#22002b5b"
				,"hoveredMaskBorder":"#ffff0000,1"
				,"fontBold":"true"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"2"
				,"paddingTop":"4"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff222530"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"center"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			}
	,"footer":{"background":"#ffe3e5e8"
				,"iconLocation":"left"
				,"border":"#ffffffff,0"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"fontFamily":"맑은 고딕"
				,"borderTop":"#a9a9a9,1"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#1f5292f7"
				,"hoveredMaskBorder":"#335292f7,1"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"1"
				,"paddingTop":"2"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff222530"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"near"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
		,"rowGroup":{"header":{"background":"linear,#fafafa,#d9d9d9,90"
//			,"rowGroup":{"header":{"background":"linear,#fafafa,#fafafa,90"
//			,"rowGroup":{"header":{"background":"#ff464c58"
				,"iconLocation":"left"
				,"border":"#ffffffff,0"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"borderTop":"#ff464c58,0"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#1f5292f7"
				,"hoveredMaskBorder":"#335292f7,1"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"2"
				,"paddingTop":"2"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ffe2ecff"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"near"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			,"footer":{"background":"#ffd8dee6"
				,"iconLocation":"left"
				,"border":"#ffffffff,0"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"fontFamily":"맑은 고딕"
				,"borderTop":"#a9a9a9,1"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#1f5292f7"
				,"hoveredMaskBorder":"#335292f7,1"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"2"
				,"paddingTop":"2"
				,"paddingRight":"4"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff000000"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"far"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			,"head":{"background":"linear,#fafafa,#d9d9d9,90"
//			,"head":{"background":"linear,#fafafa,#fafafa,90"
//			,"head":{"background":"linear,#ffffffff,#ffe7e8eb,90"
				,"iconLocation":"left"
				,"border":"#ffffffff,0"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"fontFamily":"맑은 고딕"
				,"borderTop":"#c7171d,0"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#22002b5b"
				,"hoveredMaskBorder":"#ffff0000,1"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"2"
				,"paddingTop":"2"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff222530"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"center"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			,"foot":{"background":"#ffe3e5e8"
				,"iconLocation":"left"
				,"border":"#ffffffff,0"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"fontFamily":"맑은 고딕"
				,"borderTop":"#a9a9a9,1"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#1f5292f7"
				,"hoveredMaskBorder":"#335292f7,1"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"1"
				,"paddingTop":"2"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff222530"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"near"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#ffffffff,0"
				,"iconIndex":"0"}
//			,"headerBar":{"background":"#ff464c58"
			,"headerBar":{"background":"linear,#fafafa,#d9d9d9,90"
//			,"headerBar":{"background":"linear,#fafafa,#fafafa,90"
				,"iconLocation":"left"
				,"border":"#ffffffff,0"
				,"iconAlignment":"center"
				,"borderBottom":"#ffffffff,0"
				,"fontFamily":"맑은 고딕"
				,"borderTop":"#c7171d,0"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#1f5292f7"
				,"fontSize":"5"
				,"paddingTop":"2"
				,"figureBackground":"#ffffffff"
				,"paddingBottom":"2"
				,"hoveredMaskBorder":"#335292f7,1"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ffe2ecff"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"near"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#ffffffff,0"
				,"iconIndex":"0"}
			,"footerBar":{"background":"#ffd8dee6"
				,"iconLocation":"left"
				,"border":"#ffffffff,0"
				,"iconAlignment":"center"
				,"borderBottom":"#ff6e7b8c,0"
				,"fontFamily":"맑은 고딕"
				,"borderTop":"#a9a9a9,1"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#1f5292f7"
				,"hoveredMaskBorder":"#335292f7,1"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"2"
				,"paddingTop":"2"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff000000"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"near"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			,"bar":{"background":"#ff464c58"
				,"iconLocation":"left"
				,"border":"#ffffffff,0"
				,"iconAlignment":"center"
				,"borderBottom":"#ff272d37,0"
				,"fontFamily":"맑은 고딕"
				,"borderTop":"#ff464c58,0"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#1f5292f7"
				,"fontSize":"5"
				,"paddingTop":"2"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"2"
				,"hoveredMaskBorder":"#335292f7,1"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ffe2ecff"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"near"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			,"panel":{"background":"#ff464c58"
				,"iconLocation":"left"
				,"border":"#a9a9a9,1"
				,"iconAlignment":"center"
				,"borderBottom":"#ffffffff,0"
				,"borderTop":"#c7171d,0"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#ff393c42"
				,"hoveredMaskBorder":"#335292f7,1"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"1"
				,"paddingTop":"1"
				,"paddingRight":"1"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ffe2ecff"
				,"inactiveForeground":"#ff808080"
				,"line":"#ff464c58,1"
				,"textAlignment":"center"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#ffffffff,0"
				,"iconIndex":"0"}
			}
	,"indicator":{"background":"linear,#ffffffff,#ffedeef0,360"
//	,"indicator":{"background":"linear,#fafafa,#d9d9d9,90"
//	,"indicator":{"background":"linear,#fafafa,#fafafa,90"
			,"paddingRight":"2"
			,"iconLocation":"left"
			,"border":"#a9a9a9,1"
			,"selectedForeground":"#ffffffff"
			,"iconAlignment":"center"
			,"foreground":"#ff222530"
			,"inactiveForeground":"#ff808080"
			,"borderBottom":"#a9a9a9,1"
			,"textAlignment":"center"
			,"selectedBackground":"#ffbfc6ce"
			,"lineAlignment":"center"
			,"inactiveBackground":"#ffd3d3d3"
			,"iconOffset":"0"
			,"selectionDisplay":"mask"
			,"hoveredMaskBorder":"#ff000000,1"
			,"iconPadding":"0"
			,"hoveredMaskBackground":"#ffd1d5db"
			,"contentFit":"auto"
			,"paddingTop":"2"
			,"borderRight":"#a9a9a9,1"
			,"borderLeft":"#a9a9a9,1"
			,"figureBackground":"#ff2f363f"
			,"paddingBottom":"2"
			,"iconIndex":"0"
			,"head":{"background":"linear,#fafafa,#d9d9d9,90"
//			,"head":{"background":"linear,#fafafa,#fafafa,90"
//			,"head":{"background":"linear,#ffffffff,#ffe7e8eb,90"
				,"iconLocation":"left"
				,"border":"#a9a9a9,1"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"fontFamily":"맑은 고딕"
				,"borderTop":"#c7171d,0"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#1f5292f7"
				,"hoveredMaskBorder":"#335292f7,1"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"2"
				,"paddingTop":"2"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff000000"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"center"
				,"borderLeft":"#a9a9a9,1"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			,"foot":{"background":"#ffe3e5e8"
				,"iconLocation":"left"
				,"border":"#a9a9a9,1"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"fontFamily":"맑은 고딕"
				,"borderTop":"#a9a9a9,1"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#1f5292f7"
				,"hoveredMaskBorder":"#335292f7,1"
				,"figureBackground":"#ff2f363f"
				,"paddingBottom":"2"
				,"paddingTop":"2"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff000000"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"center"
				,"borderLeft":"#a9a9a9,1"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			}
		,"checkBar":{"background":"#ffffffff"
				,"iconLocation":"left"
				,"border":"#a9a9a9,1"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"fontFamily":"맑은 고딕"
				,"iconPadding":"0"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"hoveredMaskBackground":"#1f5292f7"
				,"hoveredMaskBorder":"#335292f7,1"
				,"paddingRight":"2"
				,"paddingBottom":"2"
				,"paddingTop":"2"
				,"figureBackground":"#ff38648e"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff555555"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"center"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"
				,"head":{"background":"linear,#fafafa,#d9d9d9,90"
//				,"head":{"background":"linear,#fafafa,#fafafa,90"
//				,"head":{"background":"linear,#ffffffff,#ffe7e8eb,90"
					,"iconLocation":"left"
					,"border":"#a9a9a9,1"
					,"iconAlignment":"center"
					,"borderBottom":"#a9a9a9,1"
					,"fontFamily":"맑은 고딕"
					,"borderTop":"#c7171d,0"
					,"selectedBackground":"#ff696969"
					,"contentFit":"auto"
					,"inactiveBackground":"#ffd3d3d3"
					,"iconOffset":"0"
					,"selectionDisplay":"mask"
					,"iconPadding":"0"
					,"hoveredMaskBackground":"#1f5292f7"
					,"hoveredMaskBorder":"#335292f7,1"
					,"figureBackground":"#ff38648e"
					,"paddingBottom":"2"
					,"paddingTop":"2"
					,"paddingRight":"2"
					,"selectedForeground":"#ffffffff"
					,"foreground":"#ff000000"
					,"inactiveForeground":"#ff808080"
					,"textAlignment":"center"
					,"borderLeft":"#ffffffff,0"
					,"lineAlignment":"center"
					,"borderRight":"#a9a9a9,1"
					,"iconIndex":"0"}
			,"foot":{"background":"#ffe3e5e8"
					,"iconLocation":"left"
					,"border":"#a9a9a9,1"
					,"iconAlignment":"center"
					,"borderBottom":"#a9a9a9,1"
					,"fontFamily":"맑은 고딕"
					,"borderTop":"#a9a9a9,1"
					,"selectedBackground":"#ff696969"
					,"contentFit":"auto"
					,"inactiveBackground":"#ffd3d3d3"
					,"iconOffset":"0"
					,"selectionDisplay":"mask"
					,"iconPadding":"0"
					,"hoveredMaskBackground":"#1f5292f7"
					,"hoveredMaskBorder":"#335292f7,1"
					,"figureBackground":"#ff008800"
					,"paddingBottom":"2"
					,"paddingTop":"2"
					,"paddingRight":"2"
					,"selectedForeground":"#ffffffff"
					,"foreground":"#ff000000"
					,"inactiveForeground":"#ff808080"
					,"textAlignment":"center"
					,"borderLeft":"#ffffffff,0"
					,"lineAlignment":"center"
					,"borderRight":"#a9a9a9,1"
					,"iconIndex":"0"}
				}
	,"statusBar":{"background":"#ffffffff"
			,"iconLocation":"left"
			,"border":"#a9a9a9,1"
			,"iconAlignment":"center"
			,"borderBottom":"#a9a9a9,1"
			,"fontFamily":"맑은 고딕"
			,"iconPadding":"0"
			,"selectedBackground":"#ff696969"
			,"contentFit":"auto"
			,"inactiveBackground":"#ffd3d3d3"
			,"iconOffset":"0"
			,"selectionDisplay":"mask"
			,"hoveredMaskBackground":"#1f5292f7"
			,"hoveredMaskBorder":"#335292f7,1"
			,"paddingRight":"2"
			,"paddingBottom":"2"
			,"paddingTop":"2"
			,"figureBackground":"#ff008800"
			,"selectedForeground":"#ffffffff"
			,"foreground":"#ff000000"
			,"inactiveForeground":"#ff808080"
			,"textAlignment":"center"
			,"lineAlignment":"center"
			,"borderRight":"#a9a9a9,1"
			,"iconIndex":"0"
			,"head":{"background":"linear,#fafafa,#d9d9d9,90"
//			,"head":{"background":"linear,#fafafa,#fafafa,90"
//			,"head":{"background":"linear,#ffffffff,#ffe7e8eb,90"
				,"iconLocation":"left"
				,"border":"#a9a9a9,1"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"fontFamily":"맑은 고딕"
				,"borderTop":"#c7171d,0"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#1f5292f7"
				,"hoveredMaskBorder":"#335292f7,1"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"2"
				,"paddingTop":"2"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff000000"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"center"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			,"foot":{"background":"#ffe3e5e8"
				,"iconLocation":"left"
				,"border":"#a9a9a9,1"
				,"iconAlignment":"center"
				,"borderBottom":"#a9a9a9,1"
				,"fontFamily":"맑은 고딕"
				,"borderTop":"#a9a9a9,1"
				,"selectedBackground":"#ff696969"
				,"contentFit":"auto"
				,"inactiveBackground":"#ffd3d3d3"
				,"iconOffset":"0"
				,"selectionDisplay":"mask"
				,"iconPadding":"0"
				,"hoveredMaskBackground":"#1f5292f7"
				,"hoveredMaskBorder":"#335292f7,1"
				,"figureBackground":"#ff008800"
				,"paddingBottom":"2"
				,"paddingTop":"2"
				,"paddingRight":"2"
				,"selectedForeground":"#ffffffff"
				,"foreground":"#ff000000"
				,"inactiveForeground":"#ff808080"
				,"textAlignment":"center"
				,"borderLeft":"#ffffffff,0"
				,"lineAlignment":"center"
				,"borderRight":"#a9a9a9,1"
				,"iconIndex":"0"}
			}
	,"selection":{"background":"#2f1e90ff"
			,"paddingRight":"0"
			,"iconLocation":"left"
			,"border":"#5f1e90ff,2"
			,"selectedForeground":"#ffffffff"
			,"iconAlignment":"center"
			,"foreground":"#ff000000"
			,"inactiveForeground":"#ff808080"
			,"iconOffset":"0"
			,"textAlignment":"center"
			,"selectedBackground":"#ff696969"
			,"lineAlignment":"center"
			,"inactiveBackground":"#ffd3d3d3"
			,"selectionDisplay":"mask"
			,"hoveredMaskBorder":"#335292f7,1"
			,"iconPadding":"0"
			,"hoveredMaskBackground":"#1f5292f7"
			,"contentFit":"auto"
			,"paddingTop":"0"
			,"figureBackground":"#ff008800"
			,"paddingBottom":"0"
			,"iconIndex":"0"}
};

	
