<%@page  pageEncoding="UTF-8"%>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrsasign/8.0.20/jsrsasign-all-min.js"></script>
<script type="text/javascript" src="../js/did/CryptoWallet.js?var=190327001"></script>
<script type="text/javascript" src="../js/did/KeyValStore.js?var=190327001"></script>
<script type="text/javascript" src="../js/did/SGIndexedDB.js?var=190327001"></script>
<script type="text/javascript" src="../js/did/NdsApi.js?var=190327001"></script>