
<link rel="stylesheet" href="../css/reset.css">
<link rel="stylesheet" href="../css/common.css?var=19030501">
<link rel="stylesheet" href="../plugins/bootstrap/bootstrap.css">
<link rel="stylesheet" href="../plugins/bootstrap/bootstrap-popover-x.css">
<link rel="stylesheet" href="../plugins/jquery/jquery-ui.css">
<link rel="stylesheet" href="../plugins/jquery/jquery.scrolling-tabs.css">
<link rel="stylesheet" href="../css/custom.css?var=19030501">
<link rel="stylesheet" href="../css/content.css?var=19030501">
<link rel="stylesheet" href="../css/message.css">
<link rel="stylesheet" href="../css/commonStyle.css?var=19030501">
<link rel="stylesheet" href="../css/chatbot.css?var=19030501">
